### ISSUE TITLE
Add SourceBrowsingBehaviour

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#1]
@MLbyML
https://github.com/tischi/bdv-utils/blob/master/src/main/java/de/embl/cba/bdv/utils/behaviour/BdvBehaviours.java#L161

**Comment by NicoKiaru** [comment]
Should we keep this issue @tischi ? I'm in a big Spring cleaning of December mood.

**Comment by tischi** [comment]
Yes please leave it.

I will elaborate: This is about key-board shortcuts that allow you to go to the [N]ext and [P]revious source if you are not in fused mode. I need this for my projects.
@tibuch Do you have that in your UI anyway?

**Comment by tibuch** [comment]
No, not part of any UI component I am working on.

**Comment by NicoKiaru** [comment]
Do you have this in MoBIE @tischi ? Should we let the issue open ?
