### ISSUE TITLE
z-slider

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#100]
Hi @NicoKiaru ,
Do you know how hard it would be to add a z-slider to the BDV UI?
It would make it much easier to use for people coming from IJ.

**Comment by NicoKiaru** [comment]
I think a z slider is easy, if it has no link to sources : just have a slider with zbegin zend and nsteps. The slider set the z position and that's it 

Now if you want the step to be synchronized with multiple 2d sources stacked in z or a 3D RAI affine transformed, that's a bit more complicated. What do you think ? 

Then to attach it to the window, maybe the new UI would help, but that's another issue

**Comment by tischi** [comment]
> Then to attach it to the window, maybe the new UI would help, but that's another issue

@tpietzsch Do you have some advice as to how to attach a z-slider to BDV? I recently gave a couple of courses and I feel, in order to make the IJ1 community be more comfortable using BDV, a z-slider could be a big deal ;-)

**Comment by tischi** [comment]
> Now if you want the step to be synchronized with multiple 2d sources stacked in z or a 3D RAI affine transformed, that's a bit more complicated. What do you think ?

That is in fact a great question. I am not sure what a good z-step size would be if we have multiple sources at different voxel sizes. However, already now `,` and `.` keys have _some_ step-size. I would not know how this is set either.
@martinschorb: do you have an idea for a sensible step-size in z? Maybe we could let the user choose upon startup of the BDV?

**Comment by martinschorb** [comment]
```,```and ```.```have the same step size as the mouse wheel.

I think it would be good to really have an ability for the user to select those. Otherwise, especially for datasets with a lot of 2D data, it can easily get a bit odd.

**Comment by NicoKiaru** [comment]
See https://github.com/bigdataviewer/bigdataviewer-playground/commit/7583f2af2ff8d9f9b7ecdf692ed0dd97010854de
