### ISSUE TITLE
grouping sources

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#102]
Hi,

The Window "Bdv sources" that is used to access the sources lacks some kind of grouping.
Now, that we can get stitched tiles from BigStitcher displayed, there are several hundreds of sources (from a 15x15 tile for example) that in fact are just one source object (different ViewSetups from one xml).

I would love to have some kind of grouping possibility. Ideally automated and based on where the sources come from.

The structure is already there, shown in the different "SpimData" entries. However, naming these just numbered doesn't help in finding what is what. Would it be possible to rename those according to the input file?

**Comment by NicoKiaru** [comment]
![image](https://user-images.githubusercontent.com/20223054/78017207-34470600-734c-11ea-9f67-b1b0478603d4.png)

So you would like to have the name of the file shown instead of 'SpimData 0' ? Or would you like something more advanced ?

**Comment by martinschorb** [comment]
Yes, I think filename would be way more informative.

**Comment by martinschorb** [comment]
What I will then implement in my converter is a comprehensive naming of the ViewSetups. Something like ```ch0_tile04```

**Comment by martinschorb** [comment]
Also, the additional layer "In SpimData" in "All Sources" is not necessary. can it go?
![image](https://user-images.githubusercontent.com/35071867/78023552-1fbc3b00-7357-11ea-8baa-108231abf0dc.png)

**Comment by martinschorb** [comment]
Now that we have both sources and groups nicely integrated into the new GUI, I would love to have groups available more intuitively from our Sources manager.

Something like ```right-click -> Add to group``` -> selection of the 10 groups in BDV with their current names.
And maybe also ```remove from group``` listing every group a source belongs to if possible.

This should cover every need.

**Comment by martinschorb** [comment]
dealt with in new UI
