### ISSUE TITLE
bigWarp

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#11]
@NicoKiaru I will add one branch for bigWarp integration. I saw you had another way of doing this. So it could be interesting if you added also your variation. At least I will add you as reviewer for my PR.

**Comment by NicoKiaru** [comment]
So, you can have a look at 

https://github.com/BIOP/bigdataviewer_scijava/blob/master/src/main/java/ch/epfl/biop/bdv/scijava/command/edit/register/BigWarpInitWithBdvSources.java

to see the variation. I'm taking as an input the `SourceAndConverter` objects. This avoid to have the issue of dealing with Volatile view. Display color and range are also transfered. It also works with multiple sources. 

Also I have a second command which can output the `RealTransform` from BigWarp. The `RealTransform`is put in the objectservice and with that, I can reapply the transform to any source I'd like. It looks like what happens from minute 1 in https://www.youtube.com/watch?v=uOYWn7tUsf0

The transformation in bigdataviewer_scijava logic is also separated from Big Warp: there's a transform command (working on source and converter) which applies the transform on one or multiple `SourceAndConverter` (https://github.com/BIOP/bigdataviewer_scijava/blob/master/src/main/java/ch/epfl/biop/bdv/scijava/command/edit/transform/BdvSourcesWarp.java).

I think it's better to split the transformation from the registration, so you can mix different ones (and save you the time of coding several times the transformation)

**Comment by tischi** [comment]
Thanks!
Same question as in the PR: Do you think I should adapt my stuff or would you like to stage a PR with your version (after separating out the scijava stuff)?

**Comment by NicoKiaru** [comment]
Yep, let's discuss this in the PR ? I answered there

**Comment by NicoKiaru** [comment]
Suggestion of new BigWarp launch is in the branch newBigWarp:

https://github.com/haesleinhuepf/bigdataviewer-playground/tree/newbigwarp

**Comment by NicoKiaru** [comment]
With PR:

https://github.com/haesleinhuepf/bigdataviewer-playground/pull/39

**Comment by NicoKiaru** [comment]
PR merged
