### ISSUE TITLE
BDV settings still not capable of dealing with multiple sources

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#112]
Hi,

the settings file (main BDV window -> save settings) does not list the individual sources in a meaningful way. It is just one after the other.

Also Save Spimdataset does not store all relevant properties (ProjectionMode/ColorMap).

The question is: do we want to store one settings file for the entire atlas or one settings file for each source.

**Comment by NicoKiaru** [comment]
> main BDV window -> save settings

This do not work and I'm not sure how this will behave in the future.

For the projection Mode this can be added quite easily. 

By ColorMap do you mean lookuptable which is not a single color ? This is not really possible currently. Only single color are nicely supported right now.

**Comment by martinschorb** [comment]
I guess then maybe the menu items "File" and "Settings" should be removed.

The rest seems feasible with the ViewSetup attribute "displaysettings" and an additional one for  projectionmode.
https://github.com/bigdataviewer/bigdataviewer-playground/issues/111

**Comment by NicoKiaru** [comment]
> I guess then maybe the menu items "File" and "Settings" should be removed.

That's not part of the repo. I believe Tobias&co will have to decide what to do with it. It's probably there for legacy reasons.

**Comment by martinschorb** [comment]
dealt with using ```displaysettings```
