### ISSUE TITLE
Overlays

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#113]
Hi,

I found the cross overlay in the ortho views amazing.
Would there be a way of generating overlays (like captions/labels of certain volume regions) externally and loading them into BDV? Like this we could easily mark ROIs in our atlases...

**Comment by NicoKiaru** [comment]
Yes it's possible to generate overlays in a very modular way. Since it's very general, we need to see how to do this right - and in line with other projects.

Note that Label regions (-> a region is backed by an image = a source) is very different from an overlay (stuff you put on the screen mainly just for a convenient user display).

**Comment by martinschorb** [comment]
Cool,

is there documentation or an example file on how to get overlays in there?

I know what labels are, sorry vocabulary confusion, maybe captions i.e. text is a better word...

**Comment by martinschorb** [comment]
Would this also be the approach for displaying scale bars?

That would be an overlay of a fixed length (pixel) on screen with the caption changing based on the viewer's zoom.

**Comment by NicoKiaru** [comment]
For a complex complete example:

https://gist.github.com/tpietzsch/a2066fb2ee7b868b98a5

Cross lines in this repo (simple):

https://github.com/bigdataviewer/bigdataviewer-playground/blob/b7fc66a1a4227bf1f6d761d247acd901e9635f12/src/main/java/sc/fiji/bdvpg/scijava/command/bdv/BdvOrthoWindowCreatorCommand.java#L133-L151

**Comment by NicoKiaru** [comment]
There's already an overlay for a scalebar : https://github.com/bigdataviewer/bigdataviewer-core/blob/c48ab1de3e7ae1b2a1adcb7f8149adff1d2cfb38/src/main/java/bdv/viewer/overlay/ScaleBarOverlayRenderer.java

I can probably add it as an option to the creation of bdv viewer. Do you think it's a good idea ?

**Comment by martinschorb** [comment]
Oh definitely, https://github.com/bigdataviewer/bigdataviewer-playground/issues/76

optional Bounding boxes for volumes would also be really nice (and it seems there' s code for it already ;-) )

**Comment by martinschorb** [comment]
Now,
in order to define overlays externally and load them into BDV, one would need to create in an xml similar to a ViewSetup.

Is there anything similar existing already, or should I look into drafting a format and maybe even a parser that would draw it?

**Comment by NicoKiaru** [comment]
One possibility is to make something which can be read within the xml dataset file.

Another possibility would be to just make a groovy script which adds the overlay of your choice, like this groovy script that can launch directly from the script editor :
```

import bdv.util.*
import javax.swing.*
import java.awt.*
import net.imglib2.type.numeric.ARGBType

#@BdvHandle bdvh

final BdvOverlay overlay = new BdvOverlay(){
        protected void  draw( Graphics2D g )
        {
            int colorCode = this.info.getColor().get()
            int w = bdvh.getViewerPanel().getWidth()
            int h = bdvh.getViewerPanel().getHeight()
            g.setColor(new Color(ARGBType.red(colorCode) , ARGBType.green(colorCode), ARGBType.blue(colorCode), ARGBType.alpha(colorCode) ))
            g.drawLine((int) (w/2),(int) (h/2-h/4),(int) (w/2),(int) (h/2+h/4) );
            g.drawLine((int) (w/2-w/4),(int) (h/2),(int) (w/2+w/4),(int) (h/2) );
        }

    };

BdvFunctions.showOverlay( overlay, "overlay", BdvOptions.options().addTo( bdvh ) );
```

I have the feeling that people may want very different things as oveerlays, so I'm not so sure what a 'standard overlay' format would mean. So I'd rather start with the plan 2, and if there is something standard enough, let's try to put this into the xml dataset file

**Comment by martinschorb** [comment]
I guess the potential overlays would be: 
- static position and static size on the viewer (like the cross or the text caption of a scale bar)
- static position and dynamic size in the viewer (scale bar)
- fixed position in the data (bounding box, POI, ROI, text annotations) static size in the viewer

I will have a look and see if I can understand the BoundingBox example and get it to run with groovy.

**Comment by martinschorb** [comment]
Hi,

looking a bit deeper into BigStitcher's XML, I found a BoundingBoxes field at the end of the file. Is this BDV standard? Are there routines to show it directly from this? Or is this something specific to BigStitcher?

https://github.com/PreibischLab/BigStitcher/files/4370404/dataset.xml.zip

**Comment by NicoKiaru** [comment]
[`SpimData2`](https://github.com/PreibischLab/multiview-reconstruction/blob/master/src/main/java/net/preibisch/mvrecon/fiji/spimdata/SpimData2.java) extends `Spimdata` in multiview-reconstruction (used in BigStitcher). I do not know if it's supporting elsewhere. I guess this was introduced to store properties not directly linked to Sources, but I don't know for sure.

**Comment by martinschorb** [comment]
OK. I don't know if there's anything useful in it. Maybe we can adapt some functions though...

**Comment by martinschorb** [comment]
> 
> 
> There's already an overlay for a scalebar : https://github.com/bigdataviewer/bigdataviewer-core/blob/c48ab1de3e7ae1b2a1adcb7f8149adff1d2cfb38/src/main/java/bdv/viewer/overlay/ScaleBarOverlayRenderer.java
> 
> I can probably add it as an option to the creation of bdv viewer. Do you think it's a good idea ?

Hi,

have you looked into this? I would consider the scale bar **essential** for our publication. It will certainly be raised by reviewers. Also having an optional bounding box around selected sources (```rightClick->Show/hide Bounding Box```) would be high on my wish list.

**Comment by martinschorb** [comment]
Also, I guess there should be some  useful code here for displaying things like bounding boxes and source names...

https://github.com/bigdataviewer/bigdataviewer-core/tree/c48ab1de3e7ae1b2a1adcb7f8149adff1d2cfb38/src/main/java/bdv/viewer/overlay

**Comment by NicoKiaru** [comment]
> 
> 
> > There's already an overlay for a scalebar : https://github.com/bigdataviewer/bigdataviewer-core/blob/c48ab1de3e7ae1b2a1adcb7f8149adff1d2cfb38/src/main/java/bdv/viewer/overlay/ScaleBarOverlayRenderer.java
> > I can probably add it as an option to the creation of bdv viewer. Do you think it's a good idea ?
>  I would consider the scale bar **essential** for our publication. It will certainly be raised by reviewers. Also having an optional bounding box around selected sources 

I think all of this should go somewhere into some defaults and a config file. There are `Prefs` in Bdv, as @tischi mentioned. Yet that's in the todo

> (`rightClick->Show/hide Bounding Box`) would be high on my wish list.

That's a new action. Should be done as well.

**Comment by NicoKiaru** [comment]
I'm doing a spring cleaning. Please reopen the issue if necessary. I believe that overlays should not be dealt with in this repo, which is already quite big
