### ISSUE TITLE
Save SpimDataset, default file path

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#114]
Hi,

could the default file path be inherited from the selected Source?

![image](https://user-images.githubusercontent.com/35071867/78123328-47220f00-740e-11ea-9ae6-2a620a85b652.png)

**Comment by martinschorb** [comment]
Also, I cannot save these transformed sources :-(

```
No SpimData associated to the chosen source - aborting save Command
```

**Comment by NicoKiaru** [comment]
As discussed, the warped (=realtranstrom) transform cannot be saved easily in the current bdv file.

This would need a heavy refactoring to support this in the current SpimData format

**Comment by NicoKiaru** [comment]
I'm closing this - saving the source in a more flexible manner should be done, but that's a big deal and will need another issue
