### ISSUE TITLE
Sequential affine transformations

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#115]
Hi,

In the xml, I can define multiple affine transformations:

``` 
<ViewRegistrations>
    <ViewRegistration setup="0" timepoint="0">
      <ViewTransform type="affine">
        <affine>-0.08597637553685157 0.07168704679722755 0.0 0.0 0.07330017549416913 0.08520119819687233 0.0 0.0 0.0 0.0 1.0 0.0</affine>
        <Name>MapScaleMat</Name>
      </ViewTransform>
      <ViewTransform type="affine">
        <affine>1.0 0.0 0.0 443.608 0.0 1.0 0.0 -726.429 0.0 0.0 1.0 0.0</affine>
        <Name>Translation</Name>
      </ViewTransform>
    </ViewRegistration>
  </ViewRegistrations>
```

Why is that one different from:

```
  <ViewRegistrations>
    <ViewRegistration setup="0" timepoint="0">
      <ViewTransform type="affine">
        <affine>-0.08597637553685157 0.07168704679722755 0.0 443.608 0.07330017549416913 0.08520119819687233 0.0 -726.429 0.0 0.0 1.0 0.0</affine>
      </ViewTransform>
    </ViewRegistration>
  </ViewRegistrations>
```

I would have assumed that the transformations would be applied sequentially/combined...

![image](https://user-images.githubusercontent.com/35071867/78655595-8943c880-78c6-11ea-9b45-d55027443acc.png)

**Comment by tischi** [comment]
AffineTransforms do not commute!
Does it help if you change the order of them?

**Comment by martinschorb** [comment]
Yes

```
  <ViewRegistrations>
    <ViewRegistration setup="0" timepoint="0">
      <ViewTransform type="affine">
        <affine>1.0 0.0 0.0 443.608 0.0 1.0 0.0 -726.429 0.0 0.0 1.0 0.0</affine>
        <Name>Translation</Name>
      </ViewTransform>
      <ViewTransform type="affine">
        <affine>-0.08597637553685157 0.07168704679722755 0.0 0.0 0.07330017549416913 0.08520119819687233 0.0 0.0 0.0 0.0 1.0 0.0</affine>
        <Name>MapScaleMat</Name>
      </ViewTransform>
    </ViewRegistration>
  </ViewRegistrations>
```

works.

**Comment by martinschorb** [comment]
Would you encourage to split the transformations into the individual components for readability?

Is there a performance difference in loading them sequentially versus just a single one?

I am just re-writing parts of my converter and like to do it properly...

**Comment by martinschorb** [comment]
And BDV applies them from bottom to top, correct? Like the matrix multiplication will transform from right to left... Damn, I fell into this trap again...

**Comment by NicoKiaru** [comment]
> Is there a performance difference in loading them sequentially versus just a single one?

No. Clearly do not worry about that.

> Would you encourage to split the transformations into the individual components for readability?

Who reads an xml file ? ;-) But at least splitting between a transform that sets the voxel size and then a transform which sets the positioning in 3D is useful I find. 
In BigSticher, fi you have used it, the successive finer and finer registrations are stored as successive transforms like this. It's then easy to remove the last transform if your are not happy with it.  
Last point, in the playground, if you use manual transform, that's the difference between `append` and `mutate` : append creates a new `ViewTransform`, while mutate contatenates your transformation with the last one - so no new `ViewTransform`is created

**Comment by NicoKiaru** [comment]
> 
> 
> And BDV applies them from bottom to top, correct? Like the matrix multiplication will transform from right to left... Damn, I fell into this trap again...

I don't know where is the exact description of what's happening, but maybe have a look of this comment : https://forum.image.sc/t/big-data-viewer-xml-affine-transform/20196/3
