### ISSUE TITLE
Image Name Position

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#116]
@NicoKiaru @tpietzsch 
Do you know a way to avoid the overlapping of the image name with the time point (as in below image)?

![image](https://user-images.githubusercontent.com/2157566/78692561-603d2b00-78fa-11ea-8e19-8b2e672f155a.png)

**Comment by NicoKiaru** [comment]
Wasn't this resolved by @tpietzsch . Is that the case @tischi ?

**Comment by tischi** [comment]
Yes, I think Tobias merged an improved version of my PR.
