### ISSUE TITLE
average projector, linear interpolationartefacts at bounding box

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#117]
Hi,

I get dark bounding boxes for sources with projection mode average when applying the bdv linear interpolation.

![image](https://user-images.githubusercontent.com/35071867/78801955-90013700-79bd-11ea-9a45-70ea21b998e1.png)

The are not there with nearest-neighbour...

**Comment by NicoKiaru** [comment]
@tischi do you think that can be solved ? I don't think so, but maybe you have a clever trick ?

**Comment by NicoKiaru** [comment]
@tischi @martinschorb since it's related to the projector, I'm closing the issue here. It could be worth adding to bigdataviewer-playground-display or in MoBie
