### ISSUE TITLE
quick rotations

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#118]
Hi, 

sometimes single sources are acquired with an extra +-90 degree rotation. 
This is set entirely manually in the microscope and cannot be tracked in metadata.

To quickly adjust these wrong-oriented sources, something like ```RightClick->Rotate 90deg clockwise``` or ```rotate 180deg``` would be awesome.

**Comment by NicoKiaru** [comment]
There's an option now, but it's not accessible with a right click (see basic transformation). But my medium term goal would be to have a more flexible source editor for this sort of things

**Comment by NicoKiaru** [comment]
There's now an 'editor' mode if you press E (it's a toggle). You can then select the sources and apply the basic transformations to them.
