### ISSUE TITLE
Web viewer

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#119]
Hi,

if anyone has bunch of time to spare, there is a successful ImageJ to JavaScript translation for web browsers done together with the Dresden folks...and @tischi was there as well...

https://chemapps.stolaf.edu/swingjs/examples.htm
https://chemapps.stolaf.edu/swingjs/imagej/demo2/TestJS-core.html

If we could translate our BDV, we would have a web viewer...

**Comment by NicoKiaru** [comment]
Ouch, BDV to JS is wayyy out of scope of bdv-playground. But I've seen a number of progress towards JS/FIJI compatibility during the last hackathon in dresden. Maybe if @ctrueden has a bit of time, he can point towards some of the effort made for this ? But I think it's very early work discussed on gitter.
