### ISSUE TITLE
GenericDialog

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#12]
@haesleinhuepf 

I am sometimes using GenericDialog, for this I need some ImageJ dependency.
1. Do you think this is an issue?
1. Do you know which specific dependency that would be?

**Comment by NicoKiaru** [comment]
I'd try to keep this away as much as possible from actions, except if that's the point of the action.

For instance I think it should not be present into an Action which would transform a source. But it should be used as an action which selects a `Source` and an `AffineTransform`. Something like:

```
\\ Selecting source and transform
SelectSourceAndTransformWithGenericDialog choices = SelectSourceAndTransformWithGenericDialog().run();

\\Performing the transform
AffineTransformSource a = new AffineTransformSource(choices.getSource(), choices.getTransform());
a.run();

\\Adding the result to an existing BdvHandle
new AddSourceToBdv(bdvHandle, a.getOutputSource()).run();
```

Here the `GenericDialog` would be used in the class `SelectSourceAndTransformWithGenericDialog` only.

**Comment by tischi** [comment]
Makes sense!
I think, in fact, meanwhile this is already what happened, see e.g., here: https://github.com/haesleinhuepf/bigdataviewer-playground/blob/master/src/main/java/sc/fiji/bdv/sources/read/ui/SourcesLoaderAndAdderSwingDialog.java#L12

**Comment by NicoKiaru** [comment]
Ok, I have to say I'm a bit lost in branches - my first push will be a bit of a pain ... Let's see!

**Comment by NicoKiaru** [comment]
We can close this, please reopen if I missed something
