### ISSUE TITLE
Manual registration : Bug with timepoint indexing

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-playground#122]
The manual transform registration is applied to the previous timetpoint instead of the current one

**Comment by Pa3cia07** [comment]
Hi, I´m  interested in your project, but I am new one in open source. Could you get me some hint how run your project, please?

**Comment by NicoKiaru** [comment]
Oups, sorry @Pa3cia07 I completely missed your message ... There's a demo in https://youtu.be/LHI7vXiUUms?t=2879 if you want to have a look at how it works

**Comment by NicoKiaru** [comment]
I can't reproduce this issue - maybe it never existed
