### ISSUE TITLE
add modularity in right click and bdv default keys and mouse movements

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-playground#125]
posting the answer from @tpietzsch in gitter, in relation to bindings settings:

> https://github.com/bigdataviewer/bigdataviewer-vistools/blob/master/src/test/java/bdv/util/InputConfigExample.java
https://github.com/bigdataviewer/bigdataviewer-vistools/blob/master/src/test/java/bdv/util/InputConfigExample2.java
ui-behaviour has a nice config panel that @tinevez made
if you want to see how to use that in practice you should look at Mastodon https://github.com/mastodon-sc/mastodon
Screenshot 2020-04-24 at 10.24.05.png
BigDataViewer tries to load config files when starting
https://github.com/bigdataviewer/bigdataviewer-core/blob/61985865ec67de005f5487d617a7ae74ac3a0bb3/src/main/java/bdv/BigDataViewer.java#L637-L673
tpietzsch
@tpietzsch
10:26
"bdvkeyconfig.yaml" in current directory
"~ /.bdv/bdvkeyconfig.yaml"
if none exists use default keybindings
with respect to the configuration dialog etc, there is more to the picture
the dialog needs to know which behaviours/actions potentially exist
and everything needs to be setup such that the keybindings can be modified at runtime (which means there must be a record of all the places where actions are potentially installed)
In bigdataviewer-core, currently the keybindings are loaded ("~/.bdv/bdvkeyconfig.yaml") at startup and then not modified
I want to lift the whole infrastructure for the runtime modification/config dialog out of Mastodon
but no timeline...

**Comment by NicoKiaru** [comment]
Some progress made and merged in master branch, however it's not fully tested

**Comment by martinschorb** [comment]
is the right click now completely disabled, or can I activate it somewhere?

**Comment by NicoKiaru** [comment]
press 'E' then select sources then you can right click

I've put the novelties in https://gitter.im/bigdataviewer-playground/community

**Comment by martinschorb** [comment]
Yes I saw it there. Now I tried it, cool stuff...!

**Comment by NicoKiaru** [comment]
There's now a command `Bdv - Preferences (key) bindings` which is functional and which allows to set what commands are available depending on the context
