### ISSUE TITLE
Right-Click inside BDV image does no longer work

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#129]
Hi, 

the right-click menu as shown in the sources list does no longer appear inside the BDV window.

**Comment by NicoKiaru** [comment]
Yes, you need to associate a binding to it - which is the action which is crashing ;-)

I'll fix it and restore the default context menu with the default right click

**Comment by NicoKiaru** [comment]
That's reverted in the last fiji push, please reopen if there's still an issue
