### ISSUE TITLE
Contrast inversion

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#131]
Is there an easy way to invert the contrast?

I could not manage with setting the min and max sliders to opposite values. It does some value flips and looks weird.

**Comment by NicoKiaru** [comment]
Yes, flipping min and max works with `RealLUTConverter` but not with the standard `ColorConverter`. This would indeed be an easy way to inverse the contrast, and I don't know the reason why it doesn't work. It's more a question for @tpietzsch , if he has some time.

**Comment by NicoKiaru** [comment]
See https://github.com/bigdataviewer/bigdataviewer-core/issues/187 to follow up on this issue
