### ISSUE TITLE
Transform -> Center Source does not work in Z

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#132]
```Transform``` -> ```Center Source``` does not work in Z (moves edge to 0 instead of center)

**Comment by NicoKiaru** [comment]
This should have been fixed. Please reopen if necessary @martinschorb .

You can also check the tuto at https://youtu.be/LHI7vXiUUms?t=2884 where this function is demoed near the end of the bdv-playground part
