### ISSUE TITLE
remove source screws up average projection mode

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#133]
Hi, 

when I delete a source that is part of the average mode, it screws up the contrast of the remaining sources.

Before:
https://ibb.co/zHGZnfK

After
https://ibb.co/q9fHJmk

**Comment by martinschorb** [comment]
Hi,

there was a problem in contrast adjustment with these sources. Originally the type was signed int. This is not supported in BDV, correct?

**Comment by NicoKiaru** [comment]
It's the 'standard' xml/hdf5 format which do not support signed int. ImgLib2 can deal with it (there are `IntType` and `UnsignedIntType`) , but at the moment you would have to write your own `ImageLoader` in order to open it.

**Comment by NicoKiaru** [comment]
Hi @martinschorb, 

can you confirm if the issue is still there with the new update ?

**Comment by martinschorb** [comment]
Looks good!
