### ISSUE TITLE
UI changes Questions...

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#134]
https://github.com/bigdataviewer/bigdataviewer-playground/blob/ui-renaming/src/main/java/sc/fiji/bdvpg/scijava/services/ui/SourceAndConverterServiceUI.java l.208

This filters for `"SpimData"`, I assume we need to change this once we updated this caption...

**Comment by NicoKiaru** [comment]
I'm not sure, where they are still `SpimData`object ?

Please reopen if I missed something - also the link is outdated
