### ISSUE TITLE
Average projection mode with sources across and within BDVDatasets

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#136]
Hi,

There is some fishy behaviour with the Average projection mode when combining datasets (BDVDatasets, aka SpimData) that are composed of overlapping tiles themselves.

Here's the scenario:

- one low-magnification overview image A (one BDVDataset)
- one higher magnification tiled image B inside the low-mag (one BDVDataset containing 2x2 tiles as individual sources).

The Average projector sums the intensities and divides it by the number of sources present for each display pixel.

This leads to:

- in the center of a tile. Effect of A's intensity is **1/2**

- In the overlap zones with two tiles: `n = 1 (A) + 2 (B_00 and B_01) = 3` effect of A's intensity = **1/3**.

- In overlap zones with 4 tiles (center): `n = 1 (A) + 4 (B_00, B_01, B_10 and B_11) = 5` effect of A's intensity = **1/5**.

Ideally the Average projector would work in **two steps**:

1. Average all sources from within each BDVDataset

2. Average the result of the previous averaging across all BDVDatasets.

**Comment by NicoKiaru** [comment]
Aaaaah I think I see the issue. Honestly I think this is the sort of things that needs to be handled by a more sophisticated 'multi layer' mechanism like what you would have in illustrator, with opacity and so on.

Would be nice, but I won't have time to work on this. And even more, I think this sort of behavior should be done upstream in bdv-core.

**Comment by NicoKiaru** [comment]
related to https://github.com/bigdataviewer/bigdataviewer-playground/issues/95

**Comment by tischi** [comment]
> Here's the scenario:
    one low-magnification overview image A (one BDVDataset)
    one higher magnification tiled image B inside the low-mag (one BDVDataset containing 2x2 tiles as individual sources).

@martinschorb Could you share this dataset with me on /g/cba/exchange? 
@NicoKiaru Do you think it makes sense that I try to improve this?

**Comment by martinschorb** [comment]
> > Here's the scenario:
> > one low-magnification overview image A (one BDVDataset)
> > one higher magnification tiled image B inside the low-mag (one BDVDataset containing 2x2 tiles as individual sources).
> 
> @martinschorb Could you share this dataset with me on /g/cba/exchange?

It's in ```Martin_BDV/Overlays/```

**Comment by NicoKiaru** [comment]
This issue does belong to the projectors, which are now delegated to the  bigdataviewer-playground-display repo

**Comment by imagejan** [comment]
@NicoKiaru wrote:
> This issue does belong to the projectors, which are now delegated to the bigdataviewer-playground-display repo

For reference (as it took me a while to find where the `bigdataviewer-playground-display` repo is located, and it's not in the `bigdataviewer` org): https://github.com/BIOP/bigdataviewer-playground-display

**Comment by NicoKiaru** [comment]
Thanks @imagejan !
