### ISSUE TITLE
pyramidal TIF (single files) - hdf5 tile number limitation

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#137]
Hi,

I have single tif files that correspond to a resolution pyramid.
Is there a compatible reader to load those into BDV without conversion?

**Comment by NicoKiaru** [comment]
Not directly to my knowledge. If it's something you plan to do regularly we could do a custom loader. Maybe ask on the forum otherwise ?

**Comment by tischi** [comment]
> Is there a compatible reader to load those into BDV without conversion?

It would be possible to create such a reader, but yes, ask on the forum, or @NicoKiaru we could ask for you in bdv-core gitter?

**Comment by NicoKiaru** [comment]
> @NicoKiaru we could ask for you in bdv-core gitter?

sure

**Comment by martinschorb** [comment]
Hi,

given the size of the files (rather small), I think it would be OK to convert. I only have the problem that there are more than 100 tiles. BDV HDF5 does not support this AFAIK.

@NicoKiaru do you happen to run into the limitation with your tiled images? 

Would N5 support viewsetups with more than 2 digits?

**Comment by NicoKiaru** [comment]
@martinschorb 

I had to deal with more than a hundred tiles in bdv, not directly in xml hdf5, but there was no big issue. Bdv hdf5 CAN support these AFAIK. Did you encounter any trouble  in practice ?

**Comment by martinschorb** [comment]
The BDV h5 structure only supports 2-digit `viewsetups`. I am using n5 now. works nicely...

**Comment by NicoKiaru** [comment]
> The BDV h5 structure only supports 2-digit `viewsetups`. I am using n5 now. works nicely...

Super weird limitation! Ok, can you open n5 in bdv-playground ? If not it should be possible to make this work without too much pain.

**Comment by martinschorb** [comment]
Hi, 

n5 works. It is just slow, because it needs to do a lot of small file IO with the default chunk size of 64. For 2D tiles hdf5 would be definitely the better format. 

How tricky is the reader code to make it support more than 2 digit viewsetup IDs?

**Comment by martinschorb** [comment]
It is really slow, even with 10x (2D) bigger chunk sizes. takes multiple seconds to read in ~25 tiles. (60k files, total 170MB).

**Comment by NicoKiaru** [comment]
Who, abysmal. But are you sure the tiles are 640x640x1 and not 640x640x640 ?

Indeed I noticed that for 2D n5 was not good

**Comment by martinschorb** [comment]
It looks like chunks of 300kB to 800kB seem to be OK for N5. For 2D this means way larger chunks than default. (512x512, or 768x768)

**Comment by NicoKiaru** [comment]
OK ? Or faster than hdf5 or in the same range ? I'd be really interested to know.

**Comment by NicoKiaru** [comment]
Hi @martinschorb, 

I asked Tobias, he said there shouldn't be any issue with tile number > 99. When did you encounter the issue with tiles > 100 ? Are you sure it's not an importer problem ? Can you give us a way to reproduce your issue ?

**Comment by NicoKiaru** [comment]
@martinschorb I tried with more than 300 tiles, there was no issue with opening and saving in hdf5. Please if you still have an issue, give me a way to test and I'll look into it
