### ISSUE TITLE
edit mode -> selection in BDV UI

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#139]
Hi,

I would like to select a bunch of sources and then based on this have them selected in the (new) BDV UI as well (for grouping, adjusting contrast etc. ). So far I can only hide/show them.

**Comment by NicoKiaru** [comment]
FYI you can select sources and then based on this you can drag them to groups, using alt+click. Sources can be transfered from one window to another, etc.

In the editor mode (E key), you can select many sources, and with a right-click, you have a context menu where many actions can be performed, and what's in the list in even configurable via BDV - Set Preferences
