### ISSUE TITLE
Macro Recording

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#14]
@NicoKiaru 

@haesleinhuepf and I decided for now to not write Command wrappers around the runnable methods, to keep the dependencies minimal. It could be a layer on top that might live in another repo, such as bigdataviewer-scijava.

**Comment by NicoKiaru** [comment]
Ok doc. I'll try to give it a shot into bigdataviewer_scijava : to wrap existing behaviour into commands. This could be in theory the extra layer.

**Comment by NicoKiaru** [comment]
Obsolete : we finally adopted `Command` as a first way to build an UI.

Closing.
