### ISSUE TITLE
Caching vs. full lazy loading

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#141]
Hi,

BDV has a slightly annoying behaviour, I was wondering if this is a general appearance and due to its design or maybe something is wrong in our implementation:

- I browse a volume
- I zoom in to a particular region of interest
- BDV loads this slice in high-resolution (first the downsampled data, then progressively higher until what's needed)
- I move in the volume (1 slice further up/down)
- BDV loads this slice (first low-re then progressively higher)
- now, I go back to the view before (when I use `,` or `.` this should be the exact same view)
- why does BDV now progressively load this again? This leads to an extremely lacky browsing of volume data.
- Is there no caching? Does it keep no data in memory at all? This is not a lot, maybe a few MBs.
- Is the lazy-loading of data limited to exactly what is displayed? Wouldn't it make sense to (after loading the current view) progressively call the surrounding data and fill the memory with it to allow smooth browsing. It then wouldn't need to jump to lower resolution levels, because the high-res data should already be in memory.
- Especially when working with remote datasets, some smart caching would eliminate a lot of unnecessary traffic and loading delays.

**Comment by martinschorb** [comment]
I just tested it with MoBIE and it seems much smoother. Are there some parameters that determine to what extent it is caching data? @tischi Do you use some tricks to make the browsing smooth?

**Comment by NicoKiaru** [comment]
But with MoBie it's with n5 ? or hdf5 ?
We could do a zoom session, I'll contact you via email

**Comment by martinschorb** [comment]
Or could it be because of the downsampling factors? I do not downsample in `Z`, only `X` and `Y`...

**Comment by martinschorb** [comment]
Nailed it down to be due to looping through all sources for each pixel, even the ones outside the BoundingBox

**Comment by tischi** [comment]
In general, there is caching!
There are settings for it, it could be that with many sources something goes "wrong".

1. How many sources do you have?
1. How did you determine that it is "due to looping through all sources for each pixel, even the ones outside the BoundingBox"

> Is the lazy-loading of data limited to exactly what is displayed? 

Yes, I think so. I do not think there is any "smart pre-fetching".

**Comment by tischi** [comment]
...and does this also have if you use the "Sum projector" instead of the "Mixed projector"?

**Comment by martinschorb** [comment]
Hi,
it is also rather slow in a pure "Sum" BDV Window.

**Comment by NicoKiaru** [comment]
Recent commit should improve significantly this behaviour : when you are zoomed enough to have only a few sources visible, then only these ones are used in the projector, leading to a significant speed up. So : having many sources in a single view is slow, but as soon as you zoom in, it's much faster. For correlative stuff, it should be great.
