### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#144]
@NicoKiaru 

I just did a git pull and am getting errors:

![image](https://user-images.githubusercontent.com/2157566/88026438-28b75f00-cb36-11ea-8546-41bb17ae6c6e.png)

Any idea why?

**Comment by NicoKiaru** [comment]
Hi Tischi,

We can have a look, I suspect it's because of the extra dependency : https://github.com/NicoKiaru/bigdataviewer-selector

**Comment by NicoKiaru** [comment]
"custom" dependencies removed
