### ISSUE TITLE
problem with n5

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#145]
Hi,

I have a tile dataset stored as n5. When I load it in original BDV or BigStitcher it works (left two viewers). BDV-PG locks up when showing the sources and then only gives a black output, regardless of the contrast settings.

![image](https://user-images.githubusercontent.com/35071867/88652147-b6f98b00-d0ca-11ea-9a13-e409673d5723.png)

Data:
https://oc.embl.de/index.php/s/MWtCcWwtzWPUFMh

**Comment by NicoKiaru** [comment]
I look. Just FYi unzipping n5 is horribly slow.

**Comment by NicoKiaru** [comment]
Ok, it works in the IDE. I've updated the dependencies so maybe that solved this issue. I'll push to the update site and let you know.

**Comment by NicoKiaru** [comment]
Ok, done, pushed to the update site and it works on windows, even if there's an error message regarding blosc, it works.

Please reopen if you still have an issue @martinschorb .
