### ISSUE TITLE
Getting error in Fiji when activating the update site

### ISSUE THREAD

**Issue by ssgpers** [bigdataviewer/bigdataviewer-playground#148]
When activating this update site and restarting Fiji, always get the error shown in the screenshot

![image](https://user-images.githubusercontent.com/6419504/93718942-aa9c2680-fb7f-11ea-93b4-1b3e72d616fa.png)

**Comment by NicoKiaru** [comment]
Hi!

Have you tried on a new-fully fresh installed and updated version of FIJI ?

Just to make sure the issue is not due to another update site ...

**Comment by ssgpers** [comment]
Hi @NicoKiaru, 

I have just tried it. When getting the fresh Fiji, problem still exists.

Noticed also, that when I downgrade bigdataviewer-playground.jar manually to 0.2.0, the problem disappears. It also removes errors when using  `XmlHDF5SpimdataExporter(dataSourceAndConverters,4,0,1,4,64,64,64,File(bdvDataFolderFile,'sourcesData.xml')).run()` (for whatever reason this code stopped working today after running the update)

**Comment by NicoKiaru** [comment]
Ok, so a big update is almost ready: I'll speed it up and release it tomorrow.

I'll double check that the exporter work on FIJI (it is working in the IDE)

I'll let you know on this thread, but I think it's not worth digging on the old version.

**Comment by ssgpers** [comment]
@NicoKiaru 

Thanks a lot for the fast reply! looking forward for the updated version.

**Comment by NicoKiaru** [comment]
Done, let me know if everything's ok and please re-open if the issue is not solved

**Comment by ssgpers** [comment]
@NicoKiaru Thanks a lot! it works now without problems.
