### ISSUE TITLE
Bigwarp dependency

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#149]
@NicoKiaru 
Where can I get this file?
```
 sc.fiji:bigwarp_fiji:jar:6.0.3-SNAPSHOT-BDVCORE10
```
I can compile myself, just need the repo.

**Comment by tischi** [comment]
found it, it is just bigwarp.

**Comment by NicoKiaru** [comment]
it's on the update site or it can be recompiled from the bdv-core-10 branch of BigWarp
