### ISSUE TITLE
Version issue?

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#152]
@NicoKiaru 

I am getting this error:

```
[ERROR] Module threw error
java.lang.NoClassDefFoundError: bdv/viewer/InteractiveDisplayCanvas
	at sc.fiji.bdvpg.behaviour.EditorBehaviourInstaller.run(EditorBehaviourInstaller.java:106)
	at sc.fiji.bdvpg.bdv.BdvCreator.addBdvPlaygroundBehaviours(BdvCreator.java:200)
	at sc.fiji.bdvpg.bdv.BdvCreator.get(BdvCreator.java:168)
```

Maybe I need to have a specific bdv-core version?

**Comment by tischi** [comment]
I changed to version of bdv-core `10.0.2` but now I am getting:

```
[ERROR] Module threw error
java.lang.NoClassDefFoundError: bdv/BehaviourTransformEventHandler3D
	at bdv.util.BdvOptions$Values.<init>(BdvOptions.java:277)
	at bdv.util.BdvOptions.<init>(BdvOptions.java:51)
	at bdv.util.BdvOptions.options(BdvOptions.java:59)
	at sc.fiji.bdvpg.scijava.command.bdv.BdvWindowCreatorCommand.run(BdvWindowCreatorCommand.java:74)
```

**Comment by NicoKiaru** [comment]
Hi @tischi, 

Yes, bdv-core 10.0.2 breaks quite a few things in the transform handler. If you're lucky it's not big changes. At this point there's no turning back in bdv-playground, because of no time. I'll make the effort of reverting for bdv-bioformats and remove the dependency to bdv-playground.

There's a small discussion in gitter regarding this API modification in bdv-core

**Comment by tischi** [comment]
> Yes, bdv-core 10.0.2 breaks quite a few things in the transform handler. If you're lucky it's not big changes. 

Does it mean I should try to change the code in bdv-playground to fix this?
If so, should I just develop against `0.2.6-SNAPSHOT`?

**Comment by tischi** [comment]
Actually, the test in bdv-playground are working...

Maybe it is another issue? Maybe wrong bdv-vistools dependency...!?

**Comment by tischi** [comment]
Ok, this combination works

```
		<dependency>
			<groupId>sc.fiji</groupId>
			<artifactId>bigdataviewer-playground</artifactId>
			<version>0.2.6-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>sc.fiji</groupId>
			<artifactId>bigdataviewer-core</artifactId>
			<version>10.0.2</version>
		</dependency>

		<dependency>
			<groupId>sc.fiji</groupId>
			<artifactId>bigdataviewer-vistools</artifactId>
			<version>1.0.0-beta-23</version>
		</dependency>
```
