### ISSUE TITLE
Zoom to source

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#153]
@NicoKiaru @martinschorb 

Didn't we have a "zoom to source" menu entry at some point?

It is very useful if there are many source to zoom onto one.

![image](https://user-images.githubusercontent.com/2157566/97198835-91eee400-17af-11eb-84af-920489de46db.png)

**Comment by NicoKiaru** [comment]
The workaround is 'show sources' then keep in check 'adjust view on source'

**Comment by tischi** [comment]
> The workaround is 'show sources' then keep in check 'adjust view on source'

That works! Should I leave the issue open? I think for non-expert users we may want to discuss whether to add a specific menu item for this?!

**Comment by NicoKiaru** [comment]
Yep, let it open.
