### ISSUE TITLE
Source name ending on null

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#154]
@NicoKiaru 

Do you know why this file got the extension `-null` added? I opened it with bdv-bioformats....

![image](https://user-images.githubusercontent.com/2157566/97198995-ca8ebd80-17af-11eb-9401-c8017b1947ce.png)

**Comment by NicoKiaru** [comment]
I think it's somewhere in `bigdataviewer-bioformats` when there's no channel name. But I can't find atm where this is set

**Comment by NicoKiaru** [comment]
Closing because it's been discussed and solved in bdv-bioformats
