### ISSUE TITLE
Source grouping

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#155]
@NicoKiaru 

Do we support the grouping of sources in terms of displaySettings? I know that bdv supports it, but do we have something in the playground that I should use?

Use case: think of a multi-well plate experiment where I want to link the display settings of all GFP images in all wells.

**Comment by NicoKiaru** [comment]
There are many ways you can group sources, we need to have a small zoom session on this.

The 'tree view' is actually nodes which can be duplicated and combined. Each node is a filter for source based on a certain property.

By combining nodes you can easily select 'all sources of a certain file with a certain channel'.

**Comment by tischi** [comment]
I wanted to take this week off (at least from Zoom).
Could you maybe point me to a way how to do this programmatically? Ideally such that it also is reflected in the "normal new UI" of BDV? I don't want to do it with any UI at this point.

**Comment by NicoKiaru** [comment]
Based on which criteria woud you like to make a group ?

Then what sort of action would you like to do with this group ?

Why isn't a `List<SourceAndConverter>` enough ?

Otherwise to put Source as groups from a BdvHandle you have this for instance:
```
        SourceGroup sg = bdvHandle.getViewerPanel().state().getGroups().get(1);
        bdvHandle.getViewerPanel().state().addSourcesToGroup(sacs, sg);
```

**Comment by tischi** [comment]
I am playing with the source grouping and checking/unchecking the groups does not do anything for me:
![image](https://user-images.githubusercontent.com/2157566/99281441-ca279680-2832-11eb-8bc0-1cdfc8f5f3d8.png)
I would expect it renders the sources in the group visible / invisible? 
Did you ever try this?

**Comment by NicoKiaru** [comment]
Depends if you're in group mode or not. The group mode behaves weirdly in conjunction with the commands that can be activated with the tree view

**Comment by tischi** [comment]
Do you happen to know:

1. How could I turn on the group mode programmatically?
2. Below code looks quite good to me (I debugged into everything and it seems fine). However, I cannot see the groups in the BDV UI. Do you have any idea what I am missing?

```
	private void addSourceToGroup( HashMap< String, SourceGroup > groupIdToSourceGroup, SourceAndConverter< R > source )
	{
		String groupId = sourceToMetadata.get( source ).groupId;
		if ( ! groupIdToSourceGroup.keySet().contains( groupId ) )
		{
			groupIdToSourceGroup.put( groupId, new SourceGroup() );
		}
		SourceGroup sourceGroup = groupIdToSourceGroup.get( groupId );
		SynchronizedViewerState state = bdvHandle.getViewerPanel().state();
		state.addGroup( sourceGroup );
		state.addSourceToGroup( source, sourceGroup );
	}
```

**Comment by NicoKiaru** [comment]
I tried quickly but couldn't find a solution. I'm not sure I will use the groups anymore anyway so not sure I'll investigate

**Comment by NicoKiaru** [comment]
I'm closing this for now - there are many ways to have groups either programmatically or for the user, but this needs a more precise direction. Since I'm doing a bit of issue cleaning, when the needs come, let's open a more precise issue
