### ISSUE TITLE
Instantiate a Bdv in 2D

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#156]
@NicoKiaru 

Is there a way to do this asking for a BDV in 2D mode?

```
 SourceAndConverterServices.getSourceAndConverterDisplayService().getActiveBdv();
```

What about adding a parameters to below method in` SourceAndConverterBdvDisplayService`?
Such that one can specific whether it is 2D and the other options as well?

```
    public BdvHandle getNewBdv() {
        try
        {
            return (BdvHandle)
                    cs.run(BdvWindowCreatorCommand.class,
                            true,
                            "is2D", false,
                            "windowTitle", "Bdv",
                            "nTimepoints", 1,
                            "interpolate",false,
                            "projector", Projection.SUM_PROJECTOR).get().getOutput("bdvh");
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
        return null;
    }
```

**Comment by NicoKiaru** [comment]
`getActiveBdv` returns the last Bdv Window selected by a user, so it's already 2D or 3D. 

`getNewBdv` could be improved, but it's not my priority right now. I think that to make it right, one would need to set a lot of options, being able to configure the set of actions accessible on the right click panel, whether you want an editor mode, what are the key bindings, if it's 2d, 3d, the projector... That requires quite some work. So I put this on hold (but you will see some commands for configuration hanging around...). Also these configurations options / panel are not completely stable at the moment and are also developped by Jean Yves and Tobias. So let's wait and avoid making the work in double. 

If you want to set the parameters you can use directly the Scijava Command:

```
https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/main/java/sc/fiji/bdvpg/scijava/command/bdv/BdvWindowCreatorCommand.java
```

**Comment by tischi** [comment]
ok! let's wait then!

**Comment by NicoKiaru** [comment]
I'm closing it for now
