### ISSUE TITLE
Show Playground UI

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#158]
@NicoKiaru 
Currently the Playground Sources TreeView is already shown (in IntelliJ) when one shows the ImageJ UI, that is when executing this code and having the Playground on the class-path:

```
		ImageJ ij = new ImageJ();
		ij.ui().showUI();
```

Could we change this such that is more controllable, such that the user/developer could choose whether the Playground's Sources TreeView is shown or not? Or maybe the TreeView is only shown once the first source is added to it?

**Comment by NicoKiaru** [comment]
Done in commit https://github.com/bigdataviewer/bigdataviewer-playground/commit/033d322c628721b8c3e000b5cdac8820286e2fa9

Also there's a COmmand to force show the UI

**Comment by tischi** [comment]
Cool!
