### ISSUE TITLE
Label masks as boundaries

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#161]
@NicoKiaru 
Didn't you have some code to convert a source into another source that only shows the boundary pixels?
I have own code using a `Converter< Neighborhood< R >, R >`, which works but is somehow very slow (at least the way I am using it right now).

**Comment by NicoKiaru** [comment]
I have this gist in groovy:

https://gist.github.com/NicoKiaru/a97ede35381626c01d09cc8ea36881f3
