### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#163]
@NicoKiaru 

Currently we have

![image](https://user-images.githubusercontent.com/2157566/98437781-5de7bd00-20e5-11eb-93d6-38c8a6b46a85.png)

----

In order to stick to the general conventions in Fiji I would suggest to move this to (either):

1. Plugins > BigDataViewer > Playground > ...
1. Plugins > BigDataViewer-Playground > ...

I actually think (1) would be even nicer in terms of making the point that this aim at begin a bigdataviewer community project.

**Comment by NicoKiaru** [comment]
I vote for 2. too!

This should be a one line change here:
https://github.com/bigdataviewer/bigdataviewer-playground/blob/f48d5617abfeff8cd44128a6ac48ac790772f59e/src/main/java/sc/fiji/bdvpg/scijava/ScijavaBdvDefaults.java#L32

**Comment by tischi** [comment]
> I vote for 2. too!

which one? I was voting for 1. 😄 
```
Plugins > BigDataViewer > Playground > ...
```

**Comment by NicoKiaru** [comment]
Indeed. Option 1. Sorry too many choices ;-)

**Comment by tischi** [comment]
Awesome! Will you just do it?

**Comment by NicoKiaru** [comment]
Yep, quarantine's good for this stuff. I'll do it this evening.

**Comment by NicoKiaru** [comment]
Done in https://github.com/bigdataviewer/bigdataviewer-playground/commit/27963ccac2facb42326655b1bac7068a5163a16e
