### ISSUE TITLE
Open XML/H5 broken in current plugin release

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#164]
Hi,

in either Windows or Mac,  we can no longer open XML/h5.

The sources list simply does not appear.

**Comment by NicoKiaru** [comment]
Weird! Two things to try :

- If the window with the tree view is not visible : BigDataViewer > Show Bdv Playground Window
- Then, after opening xml / hdf5, try to double click the root node `Sources` in the tree view. If you only see:
![image](https://user-images.githubusercontent.com/20223054/99144456-5afd4700-2666-11eb-9a9a-81dc65be034a.png)
THen there's an issue

**Comment by giuliamizzon** [comment]
Hi Nico and Martin, thanks for the instructions! It worked both on Mac and Windows. 
Now the BDV Sources window appears directly upon launching Fiji and it updates when opening the files. 
Cheers, Giulia
