### ISSUE TITLE
Add source and converter via BdvFunctions

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#165]
Maybe we/you did know that but I forgot about it. 
Basically, I think I just now realised that one could always add a `SourceAndConverter` to bdv 😄 
```
Method method = BdvFunctions.class.getDeclaredMethod("addSpimDataSource", BdvHandle.class, SourceAndConverter.class, int.class );
method.setAccessible( true );
BdvStackSource< R > bdvStackSource = (BdvStackSource< R >) method.invoke( "addSpimDataSource", bdvHandle, sac, 1 );
```
You can close this as this is not really an issue, I just wanted to let you know!

**Comment by NicoKiaru** [comment]
👍 It's more for bdv-core, maybe it's be been made public already.
