### ISSUE TITLE
Mastodon dependency?

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#166]
@NicoKiaru 
![image](https://user-images.githubusercontent.com/2157566/101175434-7647ea80-3645-11eb-9a60-f6196f02e5b0.png)
Any ideas?

**Comment by NicoKiaru** [comment]
Yes that's for overriding the default bindings in bdv playground.

Some utils to do this are currently in mastodon, but I think they are supposed to move in another repo.
Pinging @tinevez  

Related : https://github.com/bigdataviewer/bigdataviewer-playground/issues/125

**Comment by tischi** [comment]
> Yes that's for overriding the default bindings in bdv playground.

What do you mean by "bindings"?

> Some utils to do this are currently in mastodon, but I think they are supposed to move in another repo.

There is so much useful stuff in mastodon, it is amazing ;-)

**Comment by NicoKiaru** [comment]
> What do you mean by "bindings"?

key bindings: which key triggers which action (like the arrows to rotate, etc.)

Part if what I did is in there : https://github.com/bigdataviewer/bigdataviewer-playground/tree/master/src/main/java/sc/fiji/bdvpg/bdv/config

**Comment by tischi** [comment]
OK! Thanks!
As you know, for this https://github.com/tischi/segmentation-annotator I am using bdv-pl as a core library without any of its UI, so I guess for this the mastodon dependency is not required, is it?

**Comment by NicoKiaru** [comment]
> As you know, for this https://github.com/tischi/segmentation-annotator I am using bdv-pl as a core library

Cool! I didn't know.

I think it's still required. Of course removing the mastodon dependency is something we need to do. But at the moment I'm not sure you can discard it from an update site (in the IDE it's ok)

**Comment by tischi** [comment]
@NicoKiaru 
Do you think you could create an issue in Mastodon, describing which classes should be factored out of Mastodon and where you think they could be moved?
cc @tinevez

**Comment by NicoKiaru** [comment]
ahaha! you're the director of operations. Yes I'll try

**Comment by tischi** [comment]
It was a suggestion from Jean-Yves (see imglib2-gitter), and since I don't know this part of code at all, I thought it is more efficient if you gave it a shot. Of course, only if you feel you have the time and resources.

**Comment by NicoKiaru** [comment]
I think we're gonna have to live with the mastodon dependency for a few more months. It's not a big deal in my opinion, but I hope the break will not be too big when what we need from mastodon will be moved elsewhere

**Comment by NicoKiaru** [comment]
Mastodon dependency removed in https://github.com/bigdataviewer/bigdataviewer-playground/commit/1ee49e6b5a1395d257903add386666255e3de55d
