### ISSUE TITLE
Utils or Helper ?

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-playground#167]
Hi @tischi and @martinschorb,

Which name do you prefer for classes which hold static useful methods ? 'Helper' or 'Utils'?

We have currently in the repo:
* SourceAndConverterUtils 
* SourceTransformHelper
* BdvUtils
* RAIHelper (this one should disappear)
* InputTriggerConfigHelper
* BdvHandleHelper (should be merged with BdvUtils)
* BvvHandleHelper
* DisplaysettingsHelper

**Comment by tischi** [comment]
Personally, I am using `Utils` a lot but I can never decide whether it should be `Utils`, `Utilities`, or `Util`.
As `Helper` does not have this issue, I am in favour for `Helper`.

And, maybe typo, but I would say `DisplaySettingsHelper` (not `DisplaysettingsHelper`).

Another common convention, bye the way, is using the Plural:

`SourceAndConverters.*`
`SourceTransforms.*`

In imglib2 for example `Intervals.*`

However that does not work well for everything, e.g., `BdvHandles` feels weird ot me.

**Comment by NicoKiaru** [comment]
Helpers ? ;-)

Ok, let's go for helper (unless @martinschorb has a strong opinion against it ?). I will refactor in a separate branch, as discussed before.

**Comment by NicoKiaru** [comment]
Refactoring done in https://github.com/bigdataviewer/bigdataviewer-playground/tree/refactor_helper
PR : https://github.com/bigdataviewer/bigdataviewer-playground/pull/169
