### ISSUE TITLE
Scijava parameters (list?) do not work with wildcards generics

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-playground#171]
The fixes-rawtype branch attempts to remove raw types in SourceAndConverter. Unfortunately, this fails with scijava input preprocessor. For some reasons, scijava attempts to put a File array into the parameter instead of a SourceAndConverter array.

Solving this needs more digging into the problematic scijava mechanism. 

For now this prevents merging the rawtype-fix branch

**Comment by tischi** [comment]
Could you paste a minimal example here? Then we could ask some knowledgable people 😃 

Is it syntax like below that fails?

```
@Parameter
SourceAndConverter<?>[] sacs
```

**Comment by NicoKiaru** [comment]
Yep, I'll try to do that!

Probably not in this repo. I think the issue is in scijava-common. I'll ping you !

**Comment by imagejan** [comment]
For the record: https://github.com/scijava/scijava-common/issues/415

**Comment by NicoKiaru** [comment]
👍 Thanks @imagejan. I'll be able to move on with this once https://github.com/scijava/scijava-common/pull/416 is merged

**Comment by imagejan** [comment]
https://github.com/scijava/scijava-common/pull/416 was merged, so we just need a new release of `scijava-common` (@ctrueden, @hinerm ?) and you should be able to proceed.

**Comment by hinerm** [comment]
@NicoKiaru @imagejan scijava-common is [slated for release in the next pom-scijava](https://github.com/scijava/pom-scijava/blob/8a0a3773744d5ac1028eb2c763c9105c5ac6ec4d/pom.xml#L324), which is waiting for [TrakEM2](https://github.com/trakem2/TrakEM2/pull/28) and [multiview-reconstruction](https://github.com/PreibischLab/multiview-reconstruction/pull/32).

**Comment by NicoKiaru** [comment]
So it's done now @hinerm ? If I update scijava pom to 30.0.0, I should have the fix, right ?

Another point : when is pom-scijava 30 supposed to be released for 'real', like in https://imagej.net/Fiji/Downloads ?

**Comment by imagejan** [comment]
@NicoKiaru not yet: https://github.com/scijava/pom-scijava/commit/b178a0b8d0d1c6efe87dada2c034930021619991 was committed *after* the `30.0.0` release, so will only be included in the next release.

(You can still manually pin to `scijava-common-2.86.1` of course, but it wouldn't work in a current Fiji without you also serving the newer `scijava-common` from your update site.)

> when is pom-scijava 30 supposed to be released for 'real', like in imagej.net/Fiji/Downloads ?

Ideally, the state of the update site should be the same as in the latest *release* of `fiji/fiji`, i.e. currently on `pom-scijava-30.0.0` in `fiji-2.2.0`:

https://github.com/fiji/fiji/blob/9f01b16ab55e5168dd111f6026386bc464a39a96/pom.xml#L5-L10

However, I don't think there was another big round of uploads after that `fiji` release, was there? /cc @hinerm

**Comment by NicoKiaru** [comment]
Working on wildcard generics fix in the branch

https://github.com/bigdataviewer/bigdataviewer-playground/tree/fix-raw

**Comment by NicoKiaru** [comment]
https://github.com/bigdataviewer/bigdataviewer-playground/tree/fix-raw Will be merged for release with scijava 32.

**Comment by NicoKiaru** [comment]
All scijava commands now have generics . Wildcards everywhere because we are working on arrays of sources which can have different types.
