### ISSUE TITLE
BigVolumeViewer dependency

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#178]
@NicoKiaru 

I tried to compile but it claimed it cannot find this dependency on maven:
```
<bigvolumeviewer.version>0.2.0</bigvolumeviewer.version>
```

**Comment by NicoKiaru** [comment]
It's on maven : https://maven.scijava.org/#nexus-search;quick~bigvolumeviewer

So normally there's no issue

What I do when dependencies are not found is to deleted the corresponding repo in cache in the temp m2 folder to force download again
