### ISSUE TITLE
Set ViewerTransform for newly added Source

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#18]
Hi @NicoKiaru, 
cc @haesleinhuepf 

Sorry again if this was already somewhere in your code, but I could not obviously find it. 
We are looking for code that, **upon adding a new Source to a bdv updates the ViewerTransform such that the newly added Source would be nicely visible**.

I found this code in your repo:     https://github.com/BIOP/bigdataviewer_scijava/blob/09fbde9aabc95259e256bd8a446dc63032584833/src/main/java/ch/epfl/biop/bdv/scijava/command/open/BdvAppendImagePlus.java#L95

But I am not sure it is doing this already and how?!

**Comment by NicoKiaru** [comment]
It's not there, except when the first source is displayed, but that's `BdvFunctions.show` which takes care of it.

The only thing I tried is this command:

[`BdvWindowTranslateCommand`](https://github.com/BIOP/bigdataviewer_scijava/blob/09fbde9aabc95259e256bd8a446dc63032584833/src/main/java/ch/epfl/biop/bdv/scijava/command/display/window/BdvWindowTranslateOnSource.java)

This command can be started from the FIIJ menu or by double clicking on the source on the JPanel UI. It's dealing with the translation only

**Comment by tischi** [comment]
Cool! Would be great to see your code as an Action in the new community repo (aka bigdataviewer playground). I will try to dig into bdv-core to see how it is done there.

**Comment by tischi** [comment]
I think I found it: https://github.com/bigdataviewer/bigdataviewer-core/blob/18e7fc18647e0e13344460f3f169825594b13a20/src/main/java/bdv/tools/InitializeViewerState.java#L94

Unfortunately it is not having the source as a parameter but is only doing it for the first source. I will copy the whole code and change this. Long term it would be nice to make a PR against BDV core to add this functionality.

**Comment by tischi** [comment]
@NicoKiaru 
It is working: 
https://github.com/haesleinhuepf/bigdataviewer-playground/blob/initViewerTransform/src/test/src/sc/fiji/bdv/navigate/ViewerTransformAdjusterDemo.java#L28

**Comment by NicoKiaru** [comment]
Very cool!

I think, in relation to https://github.com/haesleinhuepf/bigdataviewer-playground/issues/21, I'd keep this autocontrast functionality in a separate action and make a sort of composite action which would call a more  granular `autocontrast` action, acting on a source.

**Comment by tischi** [comment]
I will do this!

**Comment by NicoKiaru** [comment]
The class has been moved no ? @tischi can you point to the new class, and if everything is working, close the issue ?

**Comment by NicoKiaru** [comment]
Oups

**Comment by NicoKiaru** [comment]
I think everything is working fine, both the autocontrast (for certain types) and the vieweradjuster.
