### ISSUE TITLE
Simplify API

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#180]
```
SourceAndConverterServices.getSourceAndConverterDisplayService()
```

Maybe rename to:

```
SourceAndConverterServices.getDisplayService()
```

**Comment by NicoKiaru** [comment]
Yes, we could also think whether we want to mention that it's a bdv display service

So `getBdvDisplayService`

**Comment by tischi** [comment]
> Yes, we could also think whether we want to mention that it's a bdv display service

Good idea, because there may also be a `getBvvDisplayService` or `getSceneryDisplayService` at some point 😄
