### ISSUE TITLE
Load from S3 Object store

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#181]
Hi @NicoKiaru 
cc @constantinpape

We have code to open n5 based `spimData` when the xml is stored on S3; this currently lives in my `imagej-utils` repository.

```
public static SpimData openSpimData( String path )
	{
		try
		{
			InputStream stream = FileAndUrlUtils.getInputStream( path );
			SpimData spimData = new CustomXmlIoSpimData().loadFromStream( stream, path );
			return spimData;
		}
		catch (SpimDataException | IOException e )
		{
			System.out.println( path );
			e.printStackTrace();
			return null;
		}
	}
```

Are you interested in moving such code somewhere more accessible, e.g. inside bdv-pl?
...we would then also need to move the FileAndUrlUtils to bdv-pl...

**Comment by NicoKiaru** [comment]
We could, but actually, you can just declare the AbstractSpimData in a command of yours with a `@Parameter(type = ItemIO.OUTPUT)` annotation parameter.

So no extra dependencies.
 Bdv-playground should take it and register it.

**Comment by NicoKiaru** [comment]
> Are you interested in moving such code somewhere more accessible, e.g. inside bdv-pl?
> ...we would then also need to move the FileAndUrlUtils to bdv-pl...

I'd like to avoid as much as possible inflating the bdv-playground dependencies and number of classes (there's already a lot). It's extensible enough for a lot of things. See https://github.com/BIOP/bigdataviewer-biop-tools for instance

**Comment by tischi** [comment]
> We could, but actually, you can just declare the AbstractSpimData in a command of yours with a @Parameter(type = ItemIO.OUTPUT) annotation parameter.

OK, I have to look into this at some point. I'll leave the issue open, ok?

**Comment by NicoKiaru** [comment]
Should we still keep this issue open @tischi or could it move to another repo ?

**Comment by tischi** [comment]
We can close it.
