### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#182]
```DisplaysettingsHelper.PullDisplaySettings(out.get(setupId),setup.getAttribute(Displaysettings.class));```

should be `pullDisplaySettings` (lower case).

**Comment by NicoKiaru** [comment]
Moved to https://github.com/NicoKiaru/bigdataviewer-playground-display/issues/2

**Comment by NicoKiaru** [comment]
Done in https://github.com/BIOP/bigdataviewer-spimdata-extras/commit/619e50cdee886a1de6eef12546b17c0f87036f78
