### ISSUE TITLE
SourceTree

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#183]
It shows the source tree when I do this:

```
SourceAndConverterServices.getSourceAndConverterDisplayService().show( sourceAndConverter );
```

Can I disable this?

**Comment by NicoKiaru** [comment]
That's a modification we need to do.  I think the UI needs refactoring to avoid this situation.

**Comment by tischi** [comment]
OK, as a work-around, once the tree showed up, can I hide?

**Comment by NicoKiaru** [comment]
Probably with something like that:
```
 SourceAndConverterServices.getSourceAndConverterService().getUI().hide(); 
```

**Comment by tischi** [comment]
It still flickers quickly on and off. Should we add a global setting to disable it entirely?
Maybe: 
```
SourceAndConverterServices.getSourceAndConverterService().enableUI( boolean ) 
```

**Comment by NicoKiaru** [comment]
We need to find where it's shown automatically and remove it here. Maybe in some post processors

**Comment by tischi** [comment]
How should we make it configurable?
Some global static settings? 
`PlaygroundPrefs.showSourceTree( boolean )`

**Comment by tischi** [comment]
Maybe my proposal is not ideal, because some crazy people may use the playground and MoBIE at the same time 😉 
But doing it differently sounds annoying giving the current architecture, because dragging a parameter through into the PostProcessors may be hard?!

**Comment by NicoKiaru** [comment]
No no, we should make this modular. Also, I want to avoid depend on swing for this.

**Comment by tischi** [comment]
What do you mean by modular?

**Comment by NicoKiaru** [comment]
Sorry, it's slightly unrelated : the 'tree' is linked to a swing JPanel and JFrame. I want to get rid of this link and just keep the model, that's what I call by "modular". 

Yes, we can add a global parameter ( or prefs ) that activates auto display or not.

**Comment by NicoKiaru** [comment]
Already done with the static flag in sc.fiji.bdvpg.PlaygroundPrefs
