### ISSUE TITLE
Rename SAC

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#186]
Do we have something to rename a SAC?

**Comment by NicoKiaru** [comment]
Nope, see https://github.com/bigdataviewer/bigdataviewer-core/pull/89

In fact it's not that obvious.

**Comment by tischi** [comment]
Maybe I am also doing something wrong.

I am using `SourceAndConverterHelper.createSourceAndConverters( spimData )` and then the SAC are all called `setup0`...

The other point is that I want to change the name **just once initially** _before_ I do `SourceAndConverterDisplayService.show( sac )`.

**Comment by NicoKiaru** [comment]
Ah weird. Are they called differently if you show them using BdvFunctions.show ?

**Comment by tischi** [comment]
My mistake! They were really called "Setup0" in the xml 😸 
However, still, changing the name once, **before** adding it to the playground should not be a problem, is it? But maybe we are afraid to add functionality to change the name to the repo because than people think they also can use it **after** having shown the source...

**Comment by NicoKiaru** [comment]
> However, still, changing the name once, **before** adding it to the playground should not be a problem, is it?

I'm not sure, because there's no way to override what's being given by `SourceAndConverter.getName()`. We'll have to look.

Honestly, if we want to do this cleanly - and users will need to rename their sources - we need to be able to solve bigdataviewer/bigdataviewer-core#89

**Comment by NicoKiaru** [comment]
I'll close the issue. I don't see how to make this cleanly and functional from this repo. Please reopen if you have ideas!
