### ISSUE TITLE
num timepoints

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#189]
What's the deal with the timepoints?
Do we really have to tell BDV upon intialization how many timepoints we will have?

**Comment by NicoKiaru** [comment]
Why not ? Unfortunately, there no direct way to know how many timepoints a SourceAndConverter has. It can be infinite for instance... It's the equivalent in time of not knowing where the source is located in space. 

How would you improve this ?

**Comment by tischi** [comment]
> How would you improve this ?

I don't know... What happens if one puts too many? I guess this affects the time slider UI, does it?

**Comment by NicoKiaru** [comment]
Yes, it's just less convenient to position precisely the slider, but there's no issue apart from that.
