### ISSUE TITLE
Programmatic structure of "Bdv Actions"

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#19]
@NicoKiaru @haesleinhuepf 

I think these lines of demo code could be one good example to start discussing how we would the API to look like:

https://github.com/haesleinhuepf/bigdataviewer-playground/blob/6f56ea5d5113888e9e6337fca747a6cc5f725435/src/test/src/sc/fiji/bdv/navigate/ViewerTransformAdjusterDemo.java#L28

The same Action is called two times. Once just with constructor and run method. The second time also setting some parameters. I guess, here one could try e.g. a builder pattern.
I think especially for functions that do not return anything a builder pattern could be quite nice.

**Comment by NicoKiaru** [comment]
The builder pattern could be nice indeed but it's not ideal to get the outputs. We could think of a function to retrieve all the outputs as a `List` or a `Map`. Something like:
```
Action a = new Action(p0,p1).run();
a.getOutputs();
```
But it's not great : how to know the name of the outputs ? 

My vote here would be to keep things simple and as they are right now:
* no returned objects for input setters
* no input object for output getters

Would that work ?

**Comment by tischi** [comment]
Works for me! Simple is good!

**Comment by NicoKiaru** [comment]
We are all set. Closing this. Please reopen if necessary.
