### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#193]
Hi, right now nothing happens when I right-click into BDV.
Is there a way to enable the context menu, e.g. such that it shows everything that implement `BdvActionCommand`?
If that's more complex you could WhatsApp call me if you wish.

**Comment by NicoKiaru** [comment]
Did you press the E key? Then you activate the editor mode - you then need to select at least one source by drawing a rectangle in order to have the right click doing something. Check the neubias presentation on bdv playgroung

**Comment by tischi** [comment]
OK! And what about things like a screenshot? They would not need a source to be selected, would they?

**Comment by NicoKiaru** [comment]
Indeed, then these actions can be added directly, outside the editor mode, but this part (which actions are accessible outside the editor mode) is not modular yet.

Right now only the screenshot is activated with the D shortcut (I don't know why D...) : https://github.com/bigdataviewer/bigdataviewer-playground/blob/8695400930626fd460db393610bb19c88cfd3f54/src/main/java/sc/fiji/bdvpg/bdv/BdvCreator.java#L185-L187

**Comment by tischi** [comment]
> but this part (which actions are accessible outside the editor mode) is not modular yet.

OK, understood now, I guess that is something we could have a zoom about?! Or do you have a concrete plan already for how to do this?

**Comment by tischi** [comment]
@NicoKiaru 
How do I modify the list of available actions in the context menu during runtime?

Let's say I start like this...
```
final String[] actions = { "BDV - Screenshot" };
contextMenu = new SourceAndConverterContextMenuClickBehaviour( bdvHandle, actions );
behaviours.behaviour( contextMenu, "Sources Context Menu", "button3");
```

...and then later want to add or remove actions from the menu, is that currently possible?

If this is currently not supported, could I add this functionality by simply adding methods `addAction( String )` and `removeAction( String )` methods to `SourceAndConverterContextMenuClickBehaviour`?

**Comment by NicoKiaru** [comment]
You can add these methods `addAction` and `removeAction`, sure (currently, the action needs to be registered in the sac service before). Just a few things to keep in mind, there are alternatives to this, and I don't know which ones are suited for your use case:

* you can uninstall a behaviour and reinstall one with the new list of accessible commands
* there is the chaining mechanism which allows to completely change all behaviours if you change context (that's what is used in the editor mode)

**Comment by tischi** [comment]
> You can add these methods addAction and removeAction

will do.

> currently, the action needs to be registered in the sac service before

I know, I will keep it like this for now, because otherwise it is too much refactoring (we should probably change this together at some point during a zoom mini hackathon).

> you can uninstall a behaviour and reinstall one with the new list of accessible commands

How would that work? I mean how would that be reflected in the context menu?

**Comment by NicoKiaru** [comment]
> I know, I will keep it like this for now, because otherwise it is too much refactoring (we should probably change this together at some point during a zoom mini hackathon).

I don't think it's too much refactoring, instead (or on top of) of adding a `removeAction` and `addAction`, you can just add a `removeRunnable(String name)` and a `addRunnable(String name, Runnable run)`, no ?

**Comment by NicoKiaru** [comment]
> How would that work? I mean how would that be reflected in the context menu?

Not sure this answers your question, but in my atlas registration plugin, I have 3 behaviours:

```
Behaviours positioning_behaviours = new Behaviours(new InputTriggerConfig(), POSITIONING_MODE);
Behaviours registration_behaviours = new Behaviours(new InputTriggerConfig(), REGISTRATION_MODE);
Behaviours common_behaviours = new Behaviours(new InputTriggerConfig(), "multipositioner");
```
I have a single bdv window with several behaviours,

The common behaviours are always here (it's basically the navigation), but the two other behaviours are toggled on and off depending on the mode in which is the user, for instance, when switching from registration to positioning:

https://github.com/BIOP/ijp-imagetoatlas/blob/ad54d070281495e6d146fbea201ebffab30e16c0/src/main/java/ch/epfl/biop/atlas/aligner/MultiSlicePositioner.java#L569-L571

I'm disabling the reviewing behaviours and activating the postionining behaviours. If your right click popup window is linked to this specific behaviours (-> i.e. not defined in the common behaviours), then you have context specific popup menus.

**Comment by tischi** [comment]
The issue is 

```
		final SourceAndConverterPopupMenu popupMenu = new SourceAndConverterPopupMenu( () -> sacs.toArray(new SourceAndConverter[0]), popupActions );
```

Everything within `SourceAndConverterPopupMenu` relies on the current logic of things being registered with the `SACService`. Refactoring this seems a bit too much for now.

**Comment by NicoKiaru** [comment]
> Everything within `SourceAndConverterPopupMenu` relies on the current logic of things being registered with the `SACService`. Refactoring this seems a bit too much for now.

I see

**Comment by tischi** [comment]
Do you do a string split at `" > "` to make sub menus?

**Comment by NicoKiaru** [comment]
In popup menus ? No I don't think it's supported, is it ?

**Comment by tischi** [comment]
Not sure yet, I will check.
And if it is a Command, do do you then replicate the `menuPath`?
```
@Plugin( type=BdvPlaygroundActionCommand.class, name = "Hello World", menuPath = "BDV > Hello World" )
```

**Comment by NicoKiaru** [comment]
Nope, there's no replication. I've done it to some extent however in the atlas registration plugin, if you think this can be useful, some of it can be replicated:

https://github.com/BIOP/bigdataviewer-biop-tools/blob/a946162fac8d1be08e921f4063cf0c2c4db0000b/src/main/java/ch/epfl/biop/bdv/BdvScijavaHelper.java#L45

**Comment by tischi** [comment]
And for the names, should we try to stick to such a pattern with a static constant?

```
@Plugin( type=BdvPlaygroundActionCommand.class, name = BdvLocationLogger.NAME, menuPath = BdvLocationLogger.NAME )
public class BdvLocationLogger implements BdvPlaygroundActionCommand
{
	public static final String NAME = "BDV - Log Current Location";
}
```

That makes it more convenient to register the classes programmatically.

In fact, you are ignoring the `name` field and only consider the `menuPath`, right?

**Comment by NicoKiaru** [comment]
I think the leaf of the menupath is the same of the name, that I'm using.

> And for the names, should we try to stick to such a pattern with a static constant?

I don't really understand. You're worried about finding the name of the plugin from the class ? It can be easily done with scijava or directly by getting the annotation using java's pure reflection. I wouldn't take the pain of making a complicated pattern.

If that's convenient for you, we can make a helper class which does this.

**Comment by tischi** [comment]
This is just while coding, then I can do like this (2nd item):
```
final String[] actions = { "BDV - Screenshot", BdvLocationLogger.NAME  };
```
Otherwise I have to manually look up the name in the code.

----------------

The `"BDV - Screenshot"` is just executing for me, jumping to the `run()` method, _without_ presenting me the GUI to specify the @Parameters such as `targetPixelSizeInXY`. Do I have to do something special to enable this?

**Comment by tischi** [comment]
> If that's convenient for you, we can make a helper class which does this.

That would be nice! Where should be add it to? If you point me to the code I can do it.

**Comment by NicoKiaru** [comment]
Using standard reflection (http://tutorials.jenkov.com/java-reflection/annotations.html) that should be easy. Something like
`myClass.class.getAnnotation(Plugin.class).name`.

I don't know where to put it, a static method in the SourceAndConverterService could make sense.

**Comment by tischi** [comment]
Ok! Done!

Another question: The "BDV - Screenshot" is just executing for me, jumping to the run() method, without presenting me the GUI to specify the @Parameters such as `targetPixelSizeInXY`. Do I have to do something special to enable this?

**Comment by NicoKiaru** [comment]
> Another question: The "BDV - Screenshot" is just executing for me, jumping to the run() method, without presenting me the GUI to specify the @parameters such as `targetPixelSizeInXY`. Do I have to do something special to enable this?

Weird, no the window should popup. How do you execute it ?

**Comment by tischi** [comment]
OK, dunno why, but now it works!

**Comment by tischi** [comment]
@NicoKiaru 

In below code it does not go to the accept part, but only to the run part when being invoked via the context menu. Does that mean I should rather register it as a `Consumer< SAC[] >` (and not as a `Command.class`)?

```Java
@Plugin(type = BdvPlaygroundActionCommand.class, menuPath = ScijavaBdvDefaults.RootMenu+"Sources>Display>Set Selected Segments Coloring Mode")
public class SelectionColoringModeChangerCommand implements BdvPlaygroundActionCommand, Consumer< SourceAndConverter[] >
{
	@Override
	public void run()
	{
		IJ.log("RUN");
	}

	@Override
	public void accept( SourceAndConverter[] sourceAndConverters )
	{
		IJ.log("ACCEPT");
	}
```

**Comment by NicoKiaru** [comment]
You need to declare:
```
@Parameter
SourceAndConverter[] sourceAndConverters;
```

If you want to get your sources inside the run methods.

At the low level, sources actions are registered as Consumers of sources. But to use the GUI, you can create a BdvPlaygroundActionCommand with sources declared as input parameters.

Then, automatically, the command will be registered as a sourceandconverter action, but the consumer needs to be build. The consumer is : `(sacs) -> commandService.run(BdvCommand.class, true, "sacs", sacs);`, see https://github.com/bigdataviewer/bigdataviewer-playground/blob/dfd7182749200a96833c3b3fda87968468bbe260/src/main/java/sc/fiji/bdvpg/scijava/services/SourceAndConverterService.java#L432-L435

So Command or Consumer, but not both.

**Comment by tischi** [comment]
Thanks! Works!
