### ISSUE TITLE
ProjectionMode

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#196]
@NicoKiaru 

Are you using this in your projects?

```
public class Projection
{
	public static final String PROJECTION_MODE = "Projection Mode"; // underscore necessary for valid xml element to store in @see DisplaySettings
	public static final String PROJECTION_MODE_SUM = "Sum";
	public static final String PROJECTION_MODE_AVG = "Average";
	public static final String PROJECTION_MODE_OCCLUDING = "Occluding";

	public static final String PROJECTOR = "Projector";
	public static final String MIXED_PROJECTOR = "Mixed Projector";
	public static final String SUM_PROJECTOR = "Sum Projector";
	public static final String AVERAGE_PROJECTOR = "Average Projector";
}
```

I would like to clean this up by making it an `enum` for the projection mode.

**Comment by NicoKiaru** [comment]
Please do - from what I remember we had some troubles with scijava commands fields

**Comment by tischi** [comment]
> from what I remember we had some troubles with scijava commands fields

damn, yes....

**Comment by NicoKiaru** [comment]
Related : PR https://github.com/bigdataviewer/bigdataviewer-playground/pull/198

**Comment by NicoKiaru** [comment]
I think this is now obsolete because the projector options are not dealt with anymore in this repository, but in bigdataviewer-playground-display
