### ISSUE TITLE
Current master does not compile

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#197]
@NicoKiaru Do you know what's going on?

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/2157566/112634280-b3292e80-8e3a-11eb-8d13-2d562bd85abc.png">

**Comment by NicoKiaru** [comment]
Hum, no, what's the error message ? Maybe you have an issue in the imglib2-realtransform dependency ?

**Comment by NicoKiaru** [comment]
Sometimes you need to delete some repos in the maven cache to force download again

**Comment by tischi** [comment]
Works!
