### ISSUE TITLE
Blending of sources / custom converter

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-playground#199]
Here we can discuss plans for custom Converters and Projectors for bdv.

I just drop a few questions to start with:
* how to handle transparency ?
** at the converter level ? (identical transparency for multiple bdvs)
** at the projector level ? (transparency is a property of the current bdv)
* do we want layers ? can they be reordered ? what properties should layers have (enabled / disabled / transparency)
* what about overlays ?
* are layers sorted ?
* how is the projector aware of layers ?
* how to serialize converters (potentially layers ?)
* how to compute correctly blending ?

We should keep an eye on:
* bdv performance (we need to measure - we need benchmarks)
* making sure the events are well handled (if we go for layers, make sure the source are removed from layers if they are removed from the bdv window) (we need tests)

ping @tischi @tpietzsch @frauzufall @constantinpape @martinschorb

**Comment by tischi** [comment]
References:
- https://en.wikipedia.org/wiki/Alpha_compositing#cite_note-3
- https://github.com/saalfeldlab/paintera/tree/master/src/main/java/org/janelia/saalfeldlab/paintera/composition
