### ISSUE TITLE
Add AddSourceBehaviour

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#2]

**Comment by tischi** [comment]
- [ ] Should this also work for an empty BDV?

**Comment by NicoKiaru** [comment]
Should we keep this issue @tischi ? Then maybe detail a bit more:
Do you want to have a Behaviour that triggers a `SourceAdder` action ?

**Comment by tischi** [comment]
Let's remove it, because adding behaviours is another layer...
