### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#20]
@NicoKiaru @haesleinhuepf 

Hey guys, I forgot the outcome of our discussion: 
Did we want to put `Command`s into this repo or not?

I would be in favour of doing it because it makes it easier to actually use.

**Comment by tischi** [comment]
@NicoKiaru @haesleinhuepf 

I think I finally may understand what your worries are; citing you from imglib2/gitter

> Is there some documentation or some example of sciava.ui.behaviour 'chaining' ? I've seen this word somewhere in the documentation but I do not really understand what's its purpose and how it's supposed to be done. I've understood the concept of inputmap/actionmap but I do not grasp the difference with ui scijava behaviour(s).

Is the point that you are actually also using the `Command`s programmatically?! 
I did not get this at all! Because I personally exclusively used them to generate a GUI. 

But if we wrap the "normal" java code also into commands everybody should be happy, isn't it?

**Comment by NicoKiaru** [comment]
Regarding chaining in scijava behaviour : I have honestly no idea of what this is... I was just curious, but I really don't know if and how this could be useful to us.

For `Command`s, I think the choice was : we do not want scijava Commands dependency here. If we want to use them, we should create another repo which depends on `bigdataviewer-playground` and  wraps this repo's functionalities into Commands.

**Comment by tischi** [comment]
In principle, ok!
I am just a bit worried that we slow down ourselves with versioning and dev-ops stuff if we have this separation initially. What about we start by having a `command` package in `bigdataviewer-playground`?

**Comment by NicoKiaru** [comment]
Ok, let's just keep it at the most 'root' level so it can be easily moved in case of necessity. Would you be happy with that option @haesleinhuepf ?

**Comment by tischi** [comment]
Right now, each action has a sub-package called `ui` and that is where the respective `Command` is. I think @haesleinhuepf liked that better because it is easier to find for each action the corresponding `Command` and also while we are developing it is easier to see where we have a `Command` already and where it is still missing. The fact that it is in the clearly separate `ui` sub-package should make it easy to remove it later. I would be ok with keeping this structure for now. @NicoKiaru what do you think?

**Comment by NicoKiaru** [comment]
Oki doki! 👍

**Comment by NicoKiaru** [comment]
See https://github.com/haesleinhuepf/bigdataviewer-playground/issues/32 for a continued discussion about this `Command` vs multiple `ui` subpackages.

Closing this.
