### ISSUE TITLE
Improve determine sources at mouse position

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#203]
This can be slow as it requires a random access: `isSourcePresentAt`
This has the annoying `is2D` parameter: `isPositionWithinSourceInterval` (and maybe does not work for warped sources?)

**Comment by tischi** [comment]
@NicoKiaru Would you mind if I removed the `is2D` parameter from `isPositionWithinSourceInterval`? I just tested it and it behaves properly also for 2D sources.

**Comment by NicoKiaru** [comment]
It doesn't work if your source has a z offset and is thin, we had a discussion on gitter about this. Maybe create another method `isPositionWithinSourceInterval` with one parameter which calls `isPositionWithinSourceInterval` with a default false flag, thus assuming 3d if nothing is specified

**Comment by tischi** [comment]
OK! Then I'll leave it like this.

**Comment by NicoKiaru** [comment]
Ok, ,closing for now then
