### ISSUE TITLE
projection mode when manually transforming

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#208]
Hi,

when I manually transform a source, its projection mode in the active BDV window seems to change to **Sum**.

**Comment by NicoKiaru** [comment]
! Ok, that's probably because the sourceandconverter metadata are not duplicated. That's actually quite a big deal, because this mechanism has to be made more robust ( transfer of metadata when a source is modified).

But it is still SUM once you applied the transformation ?

**Comment by martinschorb** [comment]
It goes back to what it was set before.

**Comment by NicoKiaru** [comment]
How annoying is this issue  @martinschorb ? @tischi I could add in 'manual registration starter' as an option a function that can be applied to the wrapped sources displayed for the registration. One could imagine changing the projection mode in this optional function.

**Comment by martinschorb** [comment]
as we mostly shifted to use MoBIE for visualizing multi-source data by now, I rarely suffer from it anymore. There we can define everything in the view.

**Comment by NicoKiaru** [comment]
Ok, I think I close the issue for now then.
