### ISSUE TITLE
Transformation screwed up

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#209]
Hi,

I do the following to manually register two sources:

- manual transform 3D to scale and bring the z-Axis together
- Flip X
- manual transform in a 2D viewer to precisely register

The last manual transform gets applied the wrong way. I assume the flip is not taken into account correctly.

**Comment by martinschorb** [comment]
OK, I need to append the transformation, then it works...

**Comment by NicoKiaru** [comment]
Good point, mutate is not saved ? If that's the case, it's better to let the issue open because this needs to be solved

**Comment by NicoKiaru** [comment]
Mutate with spimdata was problematic indeed
