### ISSUE TITLE
Too much functionality in SourceAdder?

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#21]
@NicoKiaru @haesleinhuepf 

Could you guys please have a look at this code?

 https://github.com/haesleinhuepf/bigdataviewer-playground/blob/6f56ea5d5113888e9e6337fca747a6cc5f725435/src/main/java/sc/fiji/bdv/sources/read/SourceAdder.java#L22

I am confused whether there is now too much functionality in the `SourceAdder`. One could argue that it is now more like a `SourceAdderAndContrastAndViewAdjuster`. On the other hand, one could also argue that it is kind of natural for it to have all these functionalities, because they will be very often needed together. Do you have opinions and ideas how to improve this? Or is it fine like this?

**Comment by NicoKiaru** [comment]
Personally I like to have all functions separated, but it's true that chaining actions programmatically is a bit cumbersome:
Longest writing:
```
Action1 a1 = new Action1(p1,p2);
a1.run();
Out1 out1= a1.getOutput();
Action2 a2 = new Action(p3, out1);
a2.run();
Out2 out2= a2.getOutput();
Action3 a3 = new Action(p4, out2);
a3.run();
```
Or
```
Action1 a1 = new Action1(p1,p2).run();
Action2 a2 = new Action(p3, out1.getOutput()).run();
Action3 a3 = new Action(p4, a2.getOutput()).run();
```

A middle ground would be to keep actions as granular as possible (so three actions), and then reuse these three actions into a 'composite' more convenient one.

**Comment by tischi** [comment]
@NicoKiaru 

What about this thought?

On a purely programmatic level one might not need a composite class, because one can just call several actions after each other. So I think it might clutter our code when we make too many of those composite classes. In other words: I agree with you: We should keep actions separate and minimal.

However, on a `Command` level (where the UI is build) I think it might be necessary to have `Command`s that chain some actions for the user. If that is true, what about adding some more global `ui` package which contains `Command`s that are exposing composite actions?

**Comment by NicoKiaru** [comment]
Sounds like a perfect plan. Too many Commands is a mess.

**Comment by tischi** [comment]
Could you merge this? 
https://github.com/haesleinhuepf/bigdataviewer-playground/pull/24
Then I could try refactoring the `SourceAdder` as discussed.

**Comment by NicoKiaru** [comment]
Merged and refactoring done in https://github.com/haesleinhuepf/bigdataviewer-playground/commit/c2d11bce47dd152c4535b011afbecc53436ae984

Closing.
