### ISSUE TITLE
BioFormats bridge relative file paths

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#210]
Hi,

I want to use the BioFormats bridge to BDV to import a simple single image.

The file is listed in:

```
<opener_0>{"dataLocation":"...
```

However the location is an absolute file path. It seems relative paths are not supported directly in this format. However, if I want to share the data or open it from a different machine, it fails.

Would it be possible to enable a relative path to a file to open using the BioFormats bridge?

**Comment by NicoKiaru** [comment]
Ah, that's complicated. Even in QuPath they dropped the support for relative file path.

Have you tried to put a relative manually ? Does it work like this ?

**Comment by martinschorb** [comment]
> Have you tried to put a relative manually ?

It fails to find the file.

**Comment by NicoKiaru** [comment]
ok

**Comment by NicoKiaru** [comment]
This would need to be discussed in bigdataviewer-bioformats.

Honestly I don't have time to work on it.
