### ISSUE TITLE
Do not register SAC within SACHelper.createSourceAndConverters(AbstractSpimData asd)

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#214]
@NicoKiaru 

Within `SourceAndConverterHelper.createSourceAndConverters(AbstractSpimData asd)` 
the sacs are also registered in this line:

`SourceAndConverterServices.getSourceAndConverterService().register(out.get(setupId));`

Is that really necessary? 

I think I would prefer if that  helper method just created the SACS and then the registration would happen outside that function. One reason for this is that one may not necessarily have created the SACs using this code, but still would like to use the playground and thus the registration would have to be done in an extra step anyway. 

The other reason is that I think `SourceAndConverterHelper` should ideally only provide simple reusable methods that work without any Service of SciJava logic.

What do you think?

**Comment by NicoKiaru** [comment]
I think you're right.

It's quite annoying to have sources automatically registered. Maybe a good way to go is to automatically register in scijava commands only (with post processors), and then get rid of the registration in the actions ( or reusable components, or whatever you call them).

**Comment by tischi** [comment]
Good!

I see that the `show()` function within the `SourceAndConverterBdvDisplaySerivce` already registers the `sac`.

1. Are there other places where this is needed?
2. Are you currently using the `SourceAndConverterHelper.createSourceAndConverters()` _outside_ of the playground repository?
3. Should I look where `SourceAndConverterHelper.createSourceAndConverters()` is currently called _within_ the playground and add the registration after wherever this method is called?

**Comment by tischi** [comment]
ad 3. I checked within the playground and the only place where this method is called is from `SACService.register( AbstractSpimData )` and within this method the registration happens anyway. Thus, just for within the playground it looks as if we could simply remove the registration from the method.

**Comment by tischi** [comment]
I looked a bit deeper and the issue is that the SpimData contains more information (namely the `ProjectionMode`) than the `SourceAndConverter` object can represent. Thus you need to register them in order to store this extra information in the metadata store.

There are several options I think.

Option 1: Since there is a lot of stuff happening inside `SourceAndConverterHelper.createSourceAndConverters( AbstractSpimData )` I think this could deserve to be refactored into a `SourceAndConverterCreator` class. Then we could add getter methods for all the metadata that cannot be absorbed into the `SourceAndConverter`, such as the projection mode.

Option 2: We create a special `Converter` which can hold the projection mode information such that the projection mode would become part of the Converter. This would have some advantage, because within the `AccumulateProjectors` we would have the blending information directly stored within the SAC and would not have to look it up in some global metadata store.

While option 2 is interesting it would be a major design choice and probably we should wait with this until we figured out how we want to do the blending stuff in general. I would thus for now lean towards option 1, which does not include option 2, and which might anyway be handy in case we want to store and parse more non-standard metadata inside the spimData.xml.

**Comment by NicoKiaru** [comment]
> I see that the `show()` function within the `SourceAndConverterBdvDisplaySerivce` already registers the `sac`.

Ah but here this creates another issue : if we do not register the sources when they are shown, then there's no way of catching and caching the `ConverterSetup`, which is used for synchronisation of display among multiple bdv windows.

**Comment by tischi** [comment]
> if we do not register the sources when they are shown

Maybe a misunderstanding: I think it is **good** thing that `SourceAndConverterBdvDisplaySerivce.show( sac )` registers the sac, because there one is very obviously entering the world of the Services.

**Comment by NicoKiaru** [comment]
Is this issue still valid with the `sacCreator` branch merged ? @tischi , or can we close it ?

**Comment by tischi** [comment]
Thanks for the merge!!
