### ISSUE TITLE
Logging of actions

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#218]
@NicoKiaru 
Do we need this logging?
The users may think something bad happened...

<img width="448" alt="image" src="https://user-images.githubusercontent.com/2157566/117111937-9e6c7e80-ad88-11eb-96a6-1d26ec474e73.png">

**Comment by NicoKiaru** [comment]
All the logging is pretty badly done. We need to do this more cleanly for sure (with levels : debug, warning, error) see also https://github.com/bigdataviewer/bigdataviewer-playground/issues/172

**Comment by NicoKiaru** [comment]
Now using a much cleaner logging: https://github.com/bigdataviewer/bigdataviewer-playground/commit/18c32ee59d1d5305d98d24c232ce614732dada9b

**Comment by tischi** [comment]
Thanks!!
