### ISSUE TITLE
Deploying functionality to users

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#22]
My plan would be
1. create a new GitHub repo called: `bigdataviewer-embl`
1. `bigdataviewer-embl` has `bigdataviewer-playground` as a dependency
1. in `bigdataviewer-embl` there would be a Plugin that adds BDV with some of the `bigdataviewer-playground` functionality into Fiji, e.g. menuPath = **Plugins>EMBL>BigDataViewer>Open BigDataViewer**

In some future we may then converge to something more official that could be put into **Plugins>BigDataViewer>...**

Does this make sense?

@NicoKiaru @haesleinhuepf

**Comment by NicoKiaru** [comment]
Sure, why not ? I think we should create a gitter channel for all these discussions.

Do you now how to do this  @tischer or @haesleinhuepf  ?

**Comment by tischi** [comment]
Nope, don't know, do you?

**Comment by NicoKiaru** [comment]
I knew ;-) because I've created one, but I forgot. I'll look.

**Comment by NicoKiaru** [comment]
Ok,  I need to own the project or to be part of a community. I can create a
`bigdataviewer-playground` community. Is that alright for everybody ?

**Comment by tischi** [comment]
What about `bigdataviewer-community` ?

**Comment by martinschorb** [comment]
Hi,

I now got a compiled .jar from @tischi and started playing around and spamming the issues here.
However, I'd love to have a way to update myself.

**Comment by NicoKiaru** [comment]
I'll make an update site at:

`https://biop.epfl.ch/Fiji-Bdv-Playground/`

probably today, and I will let you know.

**Comment by martinschorb** [comment]
Will this require a 'virgin' Fiji installation? Otherwise it might interfere with other bdv plugins...

**Comment by NicoKiaru** [comment]
I'll test it with a 'virgin' installation. Let us know the error message if they show up. But yeah that can potentially mess your FIJI

I'm trying to do the update site now

**Comment by NicoKiaru** [comment]
I've pushed to the update site, and it looks like it's working with a fresh FIJI. Let us know what happens!

**Comment by NicoKiaru** [comment]
Hi @tischi and @martinschorb . I've pushed a new version (v0.1.4) on the update site. Let me know if there are new issues or some that have disappeared ;-)

**Comment by NicoKiaru** [comment]
Closing the thread. I added the link to the fiji update site on the readme of the repo
