### ISSUE TITLE
Showing sources first time does not work

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#227]
We have the issue that when we start the playground and for the first time want to show sources in BDV by right clicking in the source tree, a BDV window shows up, but there are no sources added.
If we do this a second time, it usually works?

Do you know what the issue could be?
Could it be related that we are missing the mastodon config file?

**Comment by NicoKiaru** [comment]
Not sure, how can I reproduce it ?

**Comment by NicoKiaru** [comment]
Could it be the time it takes for autoscale when your image is big ?

I can't reproduce this, but please reopen if needed

Closing this now
