### ISSUE TITLE
Right click options in BDV are not available

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#228]
If we right click into the BDV window there is no context menu showing up.

Is that because we are missing the settings config file?

**Comment by NicoKiaru** [comment]
New version ? It's because there's no context menu in the MinimalBdvSupplier I think, you need to set another one which includes the context menu.

What's strongly missing is some documentation about all this...

**Comment by NicoKiaru** [comment]
Closing -> this needs to be done now in the bdv supplier, cf repo https://github.com/NicoKiaru/bigdataviewer-playground-display for instance
