### ISSUE TITLE
ScreenShotMaker

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#232]
@NicoKiaru 

Sorry, I am sure I asked this before, but where did the ScreenShotMakerCommand go?

I think I remember that the issue was the the ScreenShotMaker needs to know about the AccumulateProjector and it was not clear how to handle this?

**Comment by tischi** [comment]
I guess for now I could just have the ScreenShotMaker that works with the AccumulateMixedProjector inside the MoBIE repo? And then also move the AccumulateMixedProjector into the MoBIE repo?

Long term we could maybe think about whether the BdvSupplier could also supply the corresponding Projector?

**Comment by NicoKiaru** [comment]
> Long term we could maybe think about whether the BdvSupplier could also supply the corresponding Projector?

Totally agree, we should do that and restore the ScreenShotMaker in bdv-playground, using this projector info

**Comment by NicoKiaru** [comment]
Hi Tischi, I've added a method to access the accumulator. There's a default method that needs to be overriden ( probably in https://github.com/mobie/mobie-viewer-fiji/blob/main/src/main/java/org/embl/mobie/viewer/bdv/MobieBdvSupplier.java).
I hope that'll solve this issue.

**Comment by NicoKiaru** [comment]
@tischi can this be closed ? It's an old issue, not sure what should be done anymore.
