### ISSUE TITLE
incompatible with ilastik

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#239]
Hi @NicoKiaru and @k-dominik

When I install bdv-playground running ilastik from Fiji does not show an output image anymore.

I am wondering whether the playground may do some post-processing with Command output like this: https://github.com/ilastik/ilastik4ij/blob/c3f2b21f094f3a66b537f26663fc5d6149a6cfb3/src/main/java/org/ilastik/ilastik4ij/ui/IlastikPixelClassificationCommand.java#L45
such that the output is now shown anymore?

**Comment by tischi** [comment]
To be precise ilastik does not show output images together with these dependencies: https://github.com/tischi/segmentation-annotator/blob/a43301a699101493ca188101e8264ead6d9975ae/pom.xml#L72
If you feel that a newer version of bdv-playground should not have this issue I can bump the dependencies.
It may of course also possible that some of my code is the culprit, but as I don't think I have any postprocessors in my code I thought this to be unlikely...

**Comment by NicoKiaru** [comment]
A bug in the BdvHandle postprocessor slipped through during some refactoring. It's been fixed in this commit:

https://github.com/bigdataviewer/bigdataviewer-playground/commit/34564fe1f9ad660ddf6cd8051c7ef0329a0834bd

So yes, a newer version should work

**Comment by NicoKiaru** [comment]
So far only ABBA ( experimental ) contains the new version which should fix this issue.
