### ISSUE TITLE
IntelliJ showing weird errors

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#241]
@NicoKiaru I wanted to finally look at your z-slider PR but I am having weird issues with the repo in IntelliJ:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/2157566/133045865-f7ae943c-f73f-4879-96f9-f7979fdd7a2a.png">

This is in the `raycast` branch.

The weird thing is that both maven and IntelliJ do compile the project without errors. Do you have any idea what this is about?

**Comment by NicoKiaru** [comment]
Weird - have you tried somzthing like 'invalidate cache' in intellij? That s what I try when I get weird errors like this

**Comment by NicoKiaru** [comment]
File>invalidate caches and restart

**Comment by tischi** [comment]
Thanks! That did the job!
