### ISSUE TITLE
ConverterSetup creation could support more cases

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#253]
I think the logic here could be more permissive:

```
 public static ConverterSetup createConverterSetup(SourceAndConverter sac, int legacyId) {
        //return BigDataViewer.createConverterSetup(sac, legacyId);
        ConverterSetup setup;
        if (sac.getSpimSource().getType() instanceof RealType) {
            setup = createConverterSetupRealType(sac);
        } else if (sac.getSpimSource().getType() instanceof ARGBType) {
            setup = createConverterSetupARGBType(sac);
        } else {
            errlog.accept("Cannot create convertersetup for Source of type "+sac.getSpimSource().getType().getClass().getSimpleName());
            setup = null;
        }
        //setup.setViewer(() -> requestRepaint.run());
        return setup;
    }
```

For example, the `else` case could be replace with:

```
            log.accept( "Unsupported ConverterSetup for Converters of class " +  source.getConverter().getClass() );
            if (source.asVolatile() != null) {
                setup = new UnmodifiableConverterSetup( source.getConverter(), source.asVolatile().getConverter());
            } else {
                setup = new UnmodifiableConverterSetup( source.getConverter());
            }
```

In addition, looking `createConverterSetupRealType(..)` into there is:

```
static private ConverterSetup createConverterSetupRealType(SourceAndConverter source) {
        final ConverterSetup setup;
        if (source.getConverter() instanceof ColorConverter) {
            setup = BigDataViewer.createConverterSetup(source, -1);
```

`BigDataViewer.createConverterSetup(source, ` does not require the source to be of any specific type; thus the case `source.getConverter() instanceof ColorConverter)` could be handled independent of the type of the source itself. 
In fact the return converter will not necessarily be of `RealType`.

Would it be OK if I created a PR to potentially improve this?

**Comment by NicoKiaru** [comment]
Sure, make a PR.

The lines of code for reference:

https://github.com/bigdataviewer/bigdataviewer-playground/blob/6a7e17d2a058caa644a2596b6d0c5811cb17821d/src/main/java/sc/fiji/bdvpg/sourceandconverter/SourceAndConverterHelper.java#L218-L231

Also there was an interface ([ICloneableConverter](https://github.com/bigdataviewer/bigdataviewer-playground/blob/94c947c2b908d8def28281c3706e0b5bca459a53/src/main/java/sc/fiji/bdvpg/sourceandconverter/ICloneableConverter.java)) which was made to handle particular converters in case that's useful:
https://github.com/bigdataviewer/bigdataviewer-playground/blob/6a7e17d2a058caa644a2596b6d0c5811cb17821d/src/main/java/sc/fiji/bdvpg/sourceandconverter/SourceAndConverterHelper.java#L182-L212

And why not taking `BigDataViewer.createConverterSetup(source` directly ?

**Comment by tischi** [comment]
I think `BigDataViewer.createConverterSetup()` only works for `ColorConverter`...

**Comment by tischi** [comment]
PR: https://github.com/bigdataviewer/bigdataviewer-playground/pull/255

**Comment by NicoKiaru** [comment]
PR merged. Closing this issue
