### ISSUE TITLE
Functional Programming

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#27]
Hi @NicoKiaru 

I looked at your examples!

One good thing is that it does not change the old API, it only adds functionality without too much hassle. Personally I did not use this kind fo functional programming much yet, but I am happy to learn it. So if you feel this makes our repo more useable I'd be happy to endorse this way of writing the actions.

@haesleinhuepf Do you have any opinion?

**Comment by NicoKiaru** [comment]
Just for the record, one example where the functional interface can be used:

[`GetSourceAndConverterByIndexFromBdv`](https://github.com/bigdataviewer/bigdataviewer-playground/blob/af5e7dacf7d3edb05c368d343cede0aa6394294f/src/main/java/sc/fiji/bdvpg/bdv/source/get/GetSourceAndConverterByIndexFromBdv.java) implements `Function<Integer, SourceAndConverter>`. It means that, on top of being an action, it's a function which, when given an integer, is returning a SourceAndConverter.

Let's suppose you want to get the SourceAndConverters indexed 0,1,2,5,15 from a `BdvHandle` (indexes would be of class `List<Integer>`). Here's one way you would do that without Functional Interface:

```
List<SourceAndConverters> srcs = new ArrayList<>();
for (Integer idx: indexes) {
    GetSourceAndConverterByIndexFromBdv getter = new GetSourceAndConverterByIndexFromBdv(bdvh, idx);
    getter.setOption1(opt1);
    getter.setOption2(opt2);
    ...
    getter.run();
    srcs.add(getter.getSource());
}
```

With the functional interface:

```
GetSourceAndConverterByIndexFromBdv getter = new GetSourceAndConverterByIndexFromBdv(bdvh, -1); // The index is not used in the constructor
getter.setOption1(opt1);
getter.setOption2(opt2);
...
List<SourceAndConverters> srcs = Lists.transform(indexes, getter::apply);
```

The last line applies the function on all elements of the list and returns the list of new objects.

**Comment by NicoKiaru** [comment]
Seems like this was adopted, and it's not breaking anything. Closing this. Please reopen if necessary.
