### ISSUE TITLE
BDVUtils and BdvUtils

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-playground#31]
What a mess! Case sensitivity + Java + git is awful.

We have too classes now : `BdvUtils` and `BDVUtils`. Raah I'll try to solve this and I hope not to break anything

**Comment by tischi** [comment]
Really? In my master I only see `BdvUtils`. But if there still is a `BDVUtils` please move everything to `BdvUtils` and then delete the `BDVUtils`.

**Comment by NicoKiaru** [comment]
Yeah it's in the master branch:
https://github.com/haesleinhuepf/bigdataviewer-playground/tree/master/src/main/java/sc/fiji/bdv

I'll delete it manually (if I can)

**Comment by NicoKiaru** [comment]
Done, hope it's fine
