### ISSUE TITLE
BrightnessAdjuster

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#34]
- [x] change name: `BrightnessAdjuster` to `BrightnessAutoAdjuster`
- [ ] make it work for Nico's example images

**Comment by tischi** [comment]
It currently only works for `UnsignedShortType`. We should fix this.

**Comment by NicoKiaru** [comment]
Done in https://github.com/bigdataviewer/bigdataviewer-playground/commit/af65f8b9add765cd02b2e3c275f506e48e971376
