### ISSUE TITLE
Class naming conventions

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#36]
How shall we name our classes:

`GetSourceAndConverterByIndexFromBdv`

or

`SourceAndConverterByIndexFromBdvGetter`

That is: action or noun?

@NicoKiaru

**Comment by haesleinhuepf** [comment]
IMHO Class names should be nouns while methods should be verbs.
https://www.oracle.com/technetwork/java/codeconventions-135099.html

**Comment by NicoKiaru** [comment]
So getter for class and get for method. I don't remember what I did, but amen to that.
