### ISSUE TITLE
ViewerTransform classes

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#37]
@haesleinhuepf 

Should we change the names?

- [ ] `ViewerTransformAdjuster` => `ViewerTransformAutoAdjuster`
- [ ] `ViewTransformator` => `ViewerTransformConcatenator`

In addition, I think  the correct thing in the current `ViewTransformator` would be 

```
// change the transform
view = view.preConcatenate(transform);
```

instead of
```
// change the transform
view = view.concatenate(transform);
```

**Comment by NicoKiaru** [comment]
Issue still necessary @tischi ?
