### ISSUE TITLE
getSourceIndex( bdvHandle, source )

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#41]
This function: https://github.com/haesleinhuepf/bigdataviewer-playground/blob/addcfe367d0c494fc13a33b38e1ee612606f5c36/src/main/java/sc/fiji/bdvpg/bdv/BdvUtils.java#L242

...is brittle because it assumes that we have the `Source` that `bdv` holds internally as an object, or that we know how `bdv` could have wrapped or modified it internally such that we can still identify it. It feels like that we should do something entirely different here. 

For example, one could start looking where this function is used and see what it would take to avoid calling it at all.

**Comment by NicoKiaru** [comment]
It's definitely a big issue... I guess it's the sort of issue we'll need to figure with Tobias if we do not want to write too many useless things.

Personnally, I'd say it would be better to do this completely differently:
* basically we would need a holder for all the Sources we are working on, and then we would have a function which returns all the `BdvHandle` which are displaying any `Source`. So basically a function `List<BdvHandle> getBdvHandlesDisplayingSource(source); `. 
* Then all the commands would have `@Parameter` annotations for the `Source`s being processed (or `SourceAndConverter` maybe...), and none for `BdvHandle`. Then a modification to a source would trigger a repaint action to the potentially multiple `BdvHandle`s which are displaying this source...

**Comment by tischi** [comment]
so maybe we do ask Tobias to join the Skype tomorrow?

**Comment by NicoKiaru** [comment]
Yep let's try ? It would be good to have an idea of what him and Tim-Oliver are planning.

Do you think you have time to review the BigWarp launch  (https://github.com/haesleinhuepf/bigdataviewer-playground/pull/39) before the call tomorrow ? I think it would be good to know what you think of this design, potentially you and Robert.

**Comment by tischi** [comment]
I don't have time. I have to give a talk tomorrow...

**Comment by NicoKiaru** [comment]
Ok, good luck for the talk @tischer! Maybe @haesleinhuepf , a quick look of #39 before the skype call ?

**Comment by NicoKiaru** [comment]
Indexing logic hidden inside a display service, which takes care of it.

https://github.com/bigdataviewer/bigdataviewer-playground/pull/53
