### ISSUE TITLE
viewerTransform

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#42]
@NicoKiaru 

What again is exactly the `viewerTransform`?
Is it from physical space to pixels on the screen?

**Comment by NicoKiaru** [comment]
From `ViewerState`:
```
       /**
	 * Transformation set by the interactive viewer. Transforms from global
	 * coordinate system to viewer coordinate system.
	 */
	private final AffineTransform3D viewerTransform;
```
So, I would say yes, from physical space to pixels. Does that work ?

**Comment by tischi** [comment]
I did some more tests yesterday and it looks like this indeed.
