### ISSUE TITLE
Coding style for Runnable

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#43]
I was wondering whether we should force ourselves to some coding style.

It is convenient to write:

```
new Action( bdvHandle).run()
```

More verbose is:

```
Action action = new Action( bdvHandle);
action.run()
```

The advantage of the latter is that it makes the point that sometimes it is possible that:

```
Action action = new Action( bdvHandle);
action.run()
Something something = action.getSomething();
```

**Comment by haesleinhuepf** [comment]
IMHO we shouldn't have to many rules. It is technically possible to force a coding style via maven-plugins which format code like the following which makes it easier to read:

```
new Action()
    .setParameter(5)
    .run();
```

But again I wouldn't put too many rules in our heads.

**Comment by tischi** [comment]
ok.
