### ISSUE TITLE
Branch cleaning

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-playground#46]
Hi!

Should we delete branches which have been merged ? 
So far I see these branch:
* master
* spimData
* sourceViewer
* brightnessAdjuster
* viewCapturePatch
* sourceAndConverterDemoPatch

These have been merged into master:
* sourceAndConverterDemoPatch
* sourceViewer

Should we delete these two branches which have been merged ?
Put a +1 @tischer and @haesleinhuepf and I'll do it.

PS : I have deleted the old bigwarp branch because I thought the deletion was reversible... sorry @tischi.

**Comment by tischi** [comment]
yes, please delete

**Comment by NicoKiaru** [comment]
Previously merged branches have been deleted (4 in total)
