### ISSUE TITLE
Volatile and NonVolatile Sources

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#47]
Hey @NicoKiaru ,

The way our code works right now in terms of `SourceLoader` and `SourceAdder`: it would in fact show the nonVolatile `Source`, right? 

If that's the case the current logic would actually kind of be wrong...

So, what we actually want to show is the `SourceAndConverter`, right?
So `SourceAdder( SourceAndConverter sac )`, right?

**Comment by NicoKiaru** [comment]
> The way our code works right now in terms of `SourceLoader` and `SourceAdder`: it would in fact show the nonVolatile `Source`, right?

I think so (unless you give a Volatile Source... but then it's an issue also).

> So, what we actually want to show is the SourceAndConverter, right?

Yes, but can we always do that ?
There is already a simple action to do that which I use for BigWarpLauncher (https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/main/java/sc/fiji/bdvpg/bdv/source/append/AddSourceAndConverterToBdv.java). (It needs to be renamed)

**Comment by tischi** [comment]
Yes, but doing it via the `ViewerPanel`

1. we do not get a `BdvStackSource` back, which I think is a real issue, because it might well be that this could be an important object for several things in our library.
1. did not add it to the BDV UI when I tried it, which I also think is a real issue, because we would likely not be able to benefit from @tibuch's new UI, once it is ready.

Thus, for me the way to proceed would be to get this PR merged: https://github.com/bigdataviewer/bigdataviewer-vistools/pull/40

I would even consider basing further developments on our own branch of bigdataviewer-vistools until it is merged. The point being that after our discussion yesterday I think `SourceAndConverter` and `BdvStackSource` might be key objects to work with in our playground, and, to me, the by far most natural entry point to this appears to me  `bdvss =  BdvFunctions.show( sac )`.

What do you think?

**Comment by NicoKiaru** [comment]
> 1. we do not get a `BdvStackSource` back, which I think is a real issue, because it might well be that this could be an important object for several things in our library.

Right

> 2. doing it like this does not add it to the BDV UI, which I also think is a real issue, because we would likely not be able to benefit from @tibuch's new UI, once it is ready.

Right

So we need to somehow implement your bdvvistools pr (https://github.com/bigdataviewer/bigdataviewer-playground/issues/29#issuecomment-567529812) to fix this

**Comment by tischi** [comment]
> So we need to somehow implement your bdvvistools pr (#29 (comment)) to fix this

Yes and no. I looked at it yesterday and the by far easiest way to achieve this is to simply merge the PR :-) The issue is that the code in the `BdvFunctions` calls private methods and I think it would be a bit stupid to reengineer this now when it is so easy to just add it properly to `BdvFunctions`.

As mentioned above, my suggestion would be you clone this: https://github.com/tischi/bigdataviewer-vistools/tree/displaySourceAndConverter
`mvn install` it and we work with this...

**Comment by NicoKiaru** [comment]
Oki doki, thanks.

I will not have time before the 23rd

**Comment by NicoKiaru** [comment]
We avoid using BdvVisTools and use SourceAndConverter and use our own logic.

We do not use Source anymore but directly SourceAndConverter.

See PR
https://github.com/bigdataviewer/bigdataviewer-playground/pull/53

Closing
