### ISSUE TITLE
Class names

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#5]
@haesleinhuepf 
I think those two classes should have simpler names, and also be more obvious to find as they are what potential users of this library would actually access:
- https://github.com/haesleinhuepf/bigdataviewer-playground/blob/addSource/src/main/java/sc/fiji/bdv/sourcehandling/AddSourceFromFileClickBehaviourInstaller.java#L12
- https://github.com/haesleinhuepf/bigdataviewer-playground/blob/addSource/src/main/java/sc/fiji/bdv/sourcehandling/AddSourceFromFileMenuEntryAdder.java#L12

Do you have any ideas?

**Comment by NicoKiaru** [comment]
Same question: should we keep this issue @tischi ?

The links are not valid anymore.

**Comment by imagejan** [comment]
@NicoKiaru wrote:
> The links are not valid anymore.

@tischi To avoid this in the future, use permalinks when linking to any code: simply press <kbd>Y</kbd> before copying the GitHub URL from your browser's address bar, or (for links to specific code lines) use the *Copy permalink* option in the **...** menu next to the line number.
