### ISSUE TITLE
Should we write actions for Source or for SourceAndConverter or for something else ?

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-playground#52]
Hi @tischi and @haesleinhuepf, 

A not new problem I'd like to raise again is the following: we want to deal with a source and its volatile representation, but how to achieve that ?

So far, in BdvVisTools, when we call `BdvFunctions.show(source)` or `BdvFunctions.show(spimData)` or `BdvFunctions.show(rai)` BdvFunctions tries to build the volatile view, but it can fail sometimes (see https://github.com/bigdataviewer/bigdataviewer-vistools/pull/38 for instance).

Because we would like to skip BdvVisTools, we have to deal ourselves with the volatile views. 

Let's imagine this processing:
* load a source ( no display )
* affine transform it ( no display )
* warp it ( no display )
* threshold it ( no display )
* display it

So it's 5 actions according to our repo.

Now I see two ways to deal with the volatile views:
1. either all of the actions should process `SourceAndConverter` objects, so that the volatile view is built all along the process
2. or only the display action should build the volatile view, and we keep actions with `Source` objects only - > a bit like the BdvVisTools way
3. or there's a third option, which is sort of what we are doing : a mix of both option 1 and option 2, but maybe we want to avoid that...

I try to summarize pros and cons of both options:
* Option 1 pros:
    * A clear choice is made for the actions
    * We can know easily where the volatile source chaining can fail -> and then fix it on a case by case basis
    * the cache controls can be propagated properly, if it's done right from the beginning
* Option 1 cons:
    * Not so clear reason why we should deal with SourceAndConverter objects
    * We have to deal with converters to ARGBType during all steps. That's clearly not useful when the source is not displayed. One way to avoid that is by acting on the Source and Volatile Source only and skipping the converters. Then building the converter only at the end.
    * We need to rewrite our actions 

* Option 2 pros:
    * Actions acting on Source -> makes more sense, clean and short coding
    * no need to rewrite what we did
    * the volatile wrapping code is clearly separated from the rest
* Option 2 cons:
    * maybe the volatile wrapping will not be possible, or very tedious to make in a general way
    * cache controls are lost ?

What do you think ?

**Comment by tischi** [comment]
I agree with those issues.
Shall we have a Skype?
This afternoon?

**Comment by NicoKiaru** [comment]
Decided to go with `SourceAndConverter`.
Done initially in https://github.com/bigdataviewer/bigdataviewer-playground/pull/53.
