### ISSUE TITLE
Open XML/HDF5 files -> directory does not filter for xml files

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#57]
Hi,

when opening files, the list is not filtered to only include xml files. This leads to loads of errors when it tries to open the other files in that directory.

**Comment by NicoKiaru** [comment]
Thanks for reporting! Should be solved in https://github.com/bigdataviewer/bigdataviewer-playground/commit/ac104c326928c318608826707d3fda83ac7c5526
