### ISSUE TITLE
Set Source color: no default selection

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#58]
When I set the color and leave it as it is, I get:

`'color' is required but unset`

**Comment by NicoKiaru** [comment]
Ah, you need to select it at least a color the first time. Does it solve it ?

**Comment by martinschorb** [comment]
It seems a color has to be selected at least once.
When you open the dialog another time it opens with the previous choice pre-selected.

**Comment by NicoKiaru** [comment]
https://github.com/bigdataviewer/bigdataviewer-playground/commit/5f1441c3c15bd634277c6e461b3beeb950890395
should solve this
