### ISSUE TITLE
Set Source LUT creates duplicates

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#59]
These actions create duplicate entries in the sources list. These duplicates have the identical name and do not show the changed color/LUT whatsoever in the sources list.

I suggest not creating duplicates but modifying the selected source. There is a distinct action to duplicate a source, so I would use this (please update the name to make sure it is distinguishable) and then change the color/LUT there.

**Comment by NicoKiaru** [comment]
I agree, unfortunately this cannot be done easily at the moment. However in this PR https://github.com/bigdataviewer/bigdataviewer-playground/pull/56 , if we stay with a `ColorConverter` we can modify the Color without creating a new SourceAndConverter.

Making this work with a different LUT is doable but require more work.

**Comment by martinschorb** [comment]
I see.
Naming the duplicated sources with an increasing index, or some suffix would at least avoiding the confusing duplicates in the list.

**Comment by NicoKiaru** [comment]
Yes, however modifying names or ensuring unicity of names is not straightforward because there's no accessible method that modifies the name of a `Source`.

Only if the Source is wrapped, that is an easy possibility. Honestly, for display settings, I believe the goal is to not create a new `SourceAndConverter`, but rather to build from the start a `Converter` which is modular enough in order to be able to use a complex LUT or a simple color.

**Comment by tischi** [comment]
> if we stay with a ColorConverter we can modify the Color without creating a new SourceAndConverter

I could make a `ColorChanger` class and a corresponding `ColorChangerCommand` which would give an error if the the `Converter` is not `instanceof` `ColorConverter` (or we could show a message asking the user whether they would like to create a new source with a new `Converter`). Shall I do this? I think this would solve it.

**Comment by NicoKiaru** [comment]
Actually I've done exactly this in the PR https://github.com/bigdataviewer/bigdataviewer-playground/pull/56:

https://github.com/bigdataviewer/bigdataviewer-playground/commit/daaa6cd897bf714a98059c7614c72d6fa7cb195d

**Comment by martinschorb** [comment]
Cool,

looking forward to testing it

**Comment by NicoKiaru** [comment]
I've modified the title because the color can now be changed. It's just in the case of LUT that duplicates need to be created

**Comment by martinschorb** [comment]
dealt with in new UI and new "set Color" behaviour
