### ISSUE TITLE
Set source color: show source name

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#60]
When a source color is changed for multiple sources, the selection windows opens sequentially for each one. However, it does not provide the source name, so there is no information which source is currently modified.

**Comment by NicoKiaru** [comment]
Yep, the PR https://github.com/bigdataviewer/bigdataviewer-playground/pull/56 should somehow "solve" it like this : if you select a list of Sources, the same color will be applied to all sources (and modified in place, not creating new sources).

**Comment by NicoKiaru** [comment]
PR merged, now the same color is directly applied to all sources (if they were already colored sources). And not making a new sourceandconverter if you use `Set Sources Color`.

Please reopen if necessary
