### ISSUE TITLE
Set source LUT crashes when selecting multiple sources

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#61]
`The module "sc.fiji.scijava.command.source.LUTConverterChangerCommand" failed to initialize.`

**Comment by NicoKiaru** [comment]
That fails indeed in you select multiple sources. Thanks for reporting

**Comment by NicoKiaru** [comment]
Solved in https://github.com/bigdataviewer/bigdataviewer-playground/commit/a04cc84c40afccdc27802c4dd99f0e951a517968
