### ISSUE TITLE
Add dynamic source selector (right click) in viewer

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#62]
It would be amazing to not only get the right-click menu in the source list, but also with a certain keyboard shortcut for all sources underneath the mourse cursor within a bdv window.

**Comment by NicoKiaru** [comment]
Ok, this one is really really tough! I've got no idea how to this.

**Comment by martinschorb** [comment]
@tischi already has some code that he likes to use here...

**Comment by tischi** [comment]
I can try to look into it!
