### ISSUE TITLE
add functionality to make selected source "current" and adjust view

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#63]
I am missing functionality to make a selected source (from the list) the "current" one in bdv.
Also being able to adjust the view to a selected source from the list would be very handy.

**Comment by NicoKiaru** [comment]
> Also being able to adjust the view to a selected source from the list would be very handy

Ok, that follows a discussion we had with @tischi on granularity. This function already exists but is included into an action and not as a Command.

To solve this, we should:

* Make a `Command` that runs the `ViewerTransformAdjuster` action
* Register this command to the popup window

**Comment by tischi** [comment]
I can do this.

**Comment by martinschorb** [comment]
You can work around it by "show"source and then adjust the view. It still does not become the active source yet. With the right-clicking (on the image) and the new scrollable UI, this is no longer a big problem.
