### ISSUE TITLE
lock/link several bdv windows

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#64]
I really like the functionality to work with several bdv windows in parallel.
It would be really cool to assign two/multiple of these windows to a group such that any move/rotation/zoom I do in one is also executed in the other(s).

**Comment by NicoKiaru** [comment]
This should be doable when this PR is merged:

https://github.com/bigdataviewer/bigdataviewer-playground/pull/68

**Comment by NicoKiaru** [comment]
Merged .

It's in BigDataViewer > Bdv > Synchronize Views

A window has to be closed to stop the synchronization
