### ISSUE TITLE
Remove IBdvSourceAndConverterDisplayService

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#69]
Hi @NicoKiaru,

I would propose to, for now, get rid of the interface `IBdvSourceAndConverterDisplayService`. I can do this with my next PR. The reason is that the functions in the `BdvSourceAndConverterDisplayService` are still subject to changes.
E.g. I would like to add some more functions.
It is tedious to add/remove/change them in both places. We can put back an interface once we are more certain how this should finally look like.

(Same holds true for `BdvSourceAndConverterService`)

Also, let's face it, it is very unlikely that anyone else but us would really implement a `BdvSourceAndConverterService` or a `BdvSourceAndConverterDisplayService` ;-)

**Comment by NicoKiaru** [comment]
I believe it's not a big issue a the moment and it's a good place to force us to make not too specific functions, and also it keeps the documentation in a precise location way.

I'm not saying it's super useful, but I fear that removing it could lead us to lack a structuring. It can still raise some useful discussion, like the one on the `addPopupAction`  function. We should probably improve the interface, even if there is little chance that it will be implemented twice. But who knows ? 

I think redoing the interface with BigVolumeViewer or SciView instead of BdvHandle could be worth a try, in a not too distant future.

**Comment by NicoKiaru** [comment]
I checked and one nice thing, I find, is that there is no reference to `BdvHandle` objects at all, in both interface. Hence it's possible to imagine using the same interface for SciView or BigVolumeViewer.

**Comment by tischi** [comment]
> that there is no reference to BdvHandle objects at all

What do you mean by that? 

50% of `IBdvSourceAndConverterDisplayService` methods contain  `BdvHandle`... (e.g. `void show(BdvHandle bdvh, SourceAndConverter src);`)

---

What I mainly need right now is a method to update the display of all `bdv`s containing a specific `sac`. To implement this, shall I 

1. add a dedicated method for this in `IBdvSourceAndConverterDisplayService`, or
2. add a getter method for ` Map<SourceAndConverter, List<BdvHandleRef>> sacToBdvHandleRefs;`, or 
3. do something entirely different?

---

For something else I also need to know which `sac`s are displayed in a specific `bdvHandle`. 
Again there are two choices:

1. add a dedicated method for this in `IBdvSourceAndConverterDisplayService`, or
2. add a getter method for ` Map<BdvHandle, List<SourceAndConverter>> bdvHandleToSacs;`?

---

Yet another question: 

I noticed that in this class:

```
@Plugin(type = Command.class, menuPath = ScijavaBdvDefaults.RootMenu+"Sources>Make Sources Invisible")
public class SourcesInvisibleMakerCommand implements Command {

    @Parameter
    SourceAndConverter[] sacs;

    @Parameter
    BdvSourceAndConverterDisplayService bsds;

    @Override
    public void run() {
        for (SourceAndConverter sac:sacs) {
            bsds.makeInvisible(sac);
        }
    }
}
```

...you are calling the method `bsds.makeInvisible( sac )` which is not defined in the interface `IBdvSourceAndConverterDisplayService`. Is there some logic to this or is it just a  small mistake?

**Comment by NicoKiaru** [comment]
> 50% of `IBdvSourceAndConverterDisplayService` methods contain `BdvHandle`... (e.g. `void show(BdvHandle bdvh, SourceAndConverter src);`)

Woups! Indeed, (and I was sober). Ok , so at least the `IBdvSourceAndConverterService` do not contain `BdvHandle` refs ;-), and maybe we should keep it this way, and with an interface. For the display service, we can remove the interface, I agree, but I find it nice nonetheless: we could think of a `BdvHandle` as a displayer of SourceAndConverter, and could think of it as a class variable for the display interface (maybe).

But I agree that we do not know what functions are necessary in the potential display interface, so we could just skip it for the moment.

> Is there some logic to this or is it just a small mistake?
That's a mistake.

-----
> What I mainly need right now is a method to update the display of all bdvs containing a specific sac.
> For something else I also need to know which sacs are displayed in a specific bdvHandle.

I'm not sure what's the best. I'd go for these functions in the interface:
`void updateDisplaysOf(List<SourceAndConverter> sacs);`

`List<BdvHandle> getDisplaysOf(SourceAnConverter sac);`

`List<SourceAndConverter> getSourceAndConverterOf(BdvHandle bdvHandle);`

and maybe also

`List<BdvHandle> getAllDisplays();`

Would it be ok ?

**Comment by tischi** [comment]
ok! I will then remove the interface of `IBdvSourceAndConverterDisplayService`.
We can add it back if needed.

I am raising these concerns, because I have been through this:
I wrote an interface `ImageViewer` and only called functions of the interface. Like this, I managed to write code that worked with both `Bdv` and the good old ImageJ hyperstack viewer. This was awesome conceptually, but in practice since I only used `Bdv` it was a pain. So in the end I removed the interface :-(

**Comment by tischi** [comment]
@NicoKiaru  

Am I allowed to rename?

1. `BdvSourceAndConverterService` => `SourceAndConverterService` 
1. `BdvSourceAndConverterDisplayService` => `SourceAndConverterBdvDisplayService`
1. `BdvService` => `SacServices`
1. `bdvHandle` => `bdv`

...and a **second** question:

Is it for you if I add these two methods:

`IBdvSourceAndConverterService.setMetadata( sac, String key,  Object Value )`
`IBdvSourceAndConverterService.getMetadata( sac, String key)`

I find it easier to read than handling the whole Map in the code outside of `IBdvSourceAndConverterService`.

**Comment by NicoKiaru** [comment]
:+1: for everything

Just also fyi I plan to replace whenever possible in the display service the `SourceAndConverter` argument by a 'variable' array argument:

for instance transform

`public void show(BvdHandle bdvh, SourceAndConverter sac)`

to 

`public void show(BvdHandle bdvh, SourceAndConverter... sacs);`

The reason is that when you have really a lot of source, I believe it's slow to call `requestRepaint` multiple times.

Also I believe `SourceAndConverter...` is better than `List<SourceAndConverter>` because we are dealing with arrays in most commands, and the function works if you provide a single object or an array. Maybe there is a way to specify an input argument which can indistinctly take a single object, an array or a list ? I don't know if this exists.

**Comment by tischi** [comment]
> Maybe there is a way to specify an input argument which can indistinctly take a single object, an array or a list ? I don't know if this exists.

Funny! Just few hours ago I looked at exactly this. What I did was to leave `List<SourceAndConverter>` and then call the function for a single object with `Arrays.asList( sac )`. But we can also do it with `SourceAndConverter... sacs`, maybe clearer to understand. I like it!

**Comment by NicoKiaru** [comment]
Closing this : we removed the interface for now. That was the point of this issue.

We are stuck with arrays of SourceAndConverter because that's easier to deal with in terms of scijava commands
