### ISSUE TITLE
Input to classes working on SourceAndConverter

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#74]
@NicoKiaru 

I played a bit with using `SourceAndConverter...` more often but I was not very happy, because there are some serious limitations.

1. This does not work: `Consumer< SourceAndConverter... >`
1. This does not work: `new ColorChanger( SourceAndConverter... sacs, Color color )`, because the `...` has to be in the last argument.

**Comment by NicoKiaru** [comment]
> 1. This does not work: `Consumer< SourceAndConverter... >`

No , but `Consumer< SourceAndConverter[] >` works.

> 2. 

Indeed.
Do you prefer explicit arrays ?  Do you have another idea to solve the performance issue with many sources ? I was willing to modify only the methods were there could be a performance issue.

**Comment by tischi** [comment]
> I was willing to modify only the methods were there could be a performance issue.

Sounds good! In general, I prefer `List < SourceAndConverter >`. But I have no strong opinion.

**Comment by NicoKiaru** [comment]
Closing this.

I agree List<SourceAndConverter> is better, however it does not behave well with Scijava parameters. Arrays are thus chosen at this point.
