### ISSUE TITLE
Request: slider to navigate slices

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#78]
Would it be possible to have an additional slider that would give the same functionality as the mouse wheel (moving up and down the slice)? I find it very hard to navigate larger volumes in the axial direction just using the (shift/Ctrl) Mouse wheel.

**Comment by NicoKiaru** [comment]
Hmm, how would you do that ? Like specifying a range and a number of steps ?

What sounds complicated to me to have an exact mapping between position and a `Slice`. It's not directly accessible to bigdataviewer.

Unless each slice is a different source ?

**Comment by martinschorb** [comment]
For the given view, it should be feasible to find the depth range of visible data (in bdv world units). Basically the intersection of the data with the bounding box given by the current FOV extended in the viewing direction. In fact it might be enough to just test the intersection with the corner lines of the FOV and check the extent of the data there. The minmax there would then determine the range of the slider (with n steps in between).

**Comment by NicoKiaru** [comment]
Ah now we have one! @tischi tried it. There's a demo (https://github.com/bigdataviewer/bigdataviewer-playground/blob/ef3717c9010ca89f2421dc08baefdd753c06dd48/src/test/src/sc/fiji/bdvpg/RayCastDemo.java)

It it can be added to a bdv window quite easily
