### ISSUE TITLE
place image planes

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#81]
Hi,

I just saw a talk about X-Ray Tomo and they use to browse their data in orthogonal planes.
This lead to my following ideas:

- it would be amazing to have 3 synchronized BDV windows that show the orthogonal planes at a given position/viewing orientation/zoom level.

- if the orientation of the other planes is indicated with lines, it would be fantastic to be able to rotate/place these lines in one viewer and modify the corresponding viewer accordingly.

He showed it with an example to follow a blood vessel along its main orientation and it seemed like a really nice and user-friendly way of interacting with the data visualization. 

The software offering these views is HOROS
https://horosproject.org/
that mainly deals with DICOM.

**Comment by NicoKiaru** [comment]
>     it would be amazing to have 3 synchronized BDV windows that show the orthogonal planes at a given position/viewing orientation/zoom level.

This shouldn't be too much work.
Not sure your link is working.

>  if the orientation of the other planes is indicated with lines, it would be fantastic to be able to rotate/place these lines in one viewer and modify the corresponding viewer accordingly.

This is more work. I have no idea how to display overlays on bdv actually. @tischi knows more

**Comment by tischi** [comment]
> This is more work

Out of scope currently. And also something that we probably should not work on our own but do it together with, e.g. @maartz because he was thinking about orthogonal planes viewing for labKit, afaik.

**Comment by martinschorb** [comment]
This is the wrong developer...
@maarzt is who might be needed!

**Comment by maarzt** [comment]
I don't think I will have orthogonal planes in Labkit any time soon. But Paintera https://github.com/saalfeldlab/paintera already uses BDV to show orthogonal planes. But it's based on JavaFX and that's not compatible with the ImageJ swing UI. If there's a working prototype, I'm happy to have a look at it.

**Comment by NicoKiaru** [comment]
I have a draft for orthoviews here:

https://github.com/bigdataviewer/bigdataviewer-playground/blob/orthoview/src/main/java/sc/fiji/bdvpg/bdv/navigate/ViewerOrthoSyncStarter.java

The issue I have is that it's not centered on the center of the bdv window, but on its top left corner. And with the trick I use to synchronize both windows, it's gonna be a bit painful to center it correctly.

**Comment by NicoKiaru** [comment]
There is an ortho view for quite some time now:

https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/main/java/sc/fiji/bdvpg/scijava/command/bdv/BdvOrthoWindowCreatorCommand.java

The interface can be improved, but I'll close the issue. If there are improvements needed for the UI, then let's open another issue
