### ISSUE TITLE
capture view

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#82]
@NicoKiaru I need to implement a new view capture that simply returns a RGB image.
You once mentioned that you also have code for capturing the current view. Could you point me to it to have a look?

**Comment by NicoKiaru** [comment]
I don't know if that helps, but here's my implementation:

https://github.com/BIOP/bigdataviewer_scijava/blob/master/src/main/java/ch/epfl/biop/bdv/scijava/command/export/BdvSourcesBdvViewToImagePlus.java

It outputs RGB image, but only if the source is RGB.

**Comment by tischi** [comment]
Looks good......  
Do you have a feeling for whether this is significantly different from what we currently have?

https://github.com/bigdataviewer/bigdataviewer-playground/blob/be40dd31bf4a2ead6a02894f57aa975d20188d92/src/main/java/sc/fiji/bdvpg/bdv/ScreenShotMaker.java#L77

Just glancing over both codes I had the feeling it might be more or less the same?

**Comment by NicoKiaru** [comment]
I may have forgotten things, but here's how it compares

Supported in my implementation and not in screenshotmaker (to my knowledge):
- All RealType Source (FloatType to float for instance) + ARGBSource to RGB ImagePlus
- Export of ImageJ1 ImagePlus Calibration (XYZ spacings and offsets)
- Export of z stack (with different z spacing)

Supported in ScreenShotMaker and not in mine:
- Automatic choice of mimap level
- Segmentation ? Glasbey image

Difference in implementation (not good or bad, may have performance difference depending on use cases):
- Virtual stack vs non virtual stack
- My impl : parallelization made on sources vs ScreenShotMaker : parallelization wihin one image with grid access
- Compulsory explicit choice of xy voxel size in mine
- Compulsory explicit choice of source in mine

**Comment by tischi** [comment]
code is still horrible, but I think I implemented a good functionality:
https://github.com/embl-cba/fiji-plugin-platyBrowser/issues/47

**Comment by martinschorb** [comment]
Is this functionality available in the current version?
Would typing C do it? 
Instead of opening a new ImageJ window, could I create a stack/movie by pressing c multiple times while browsing/zooming/rotating through the volume?

**Comment by tischi** [comment]
to make a movie I would probably just use some screen casting tools like QuickTime Player.

**Comment by tischi** [comment]
regarding typing C: I still have to create a PR to add the functionality.

**Comment by martinschorb** [comment]
That makes sense if we wanted to just capture exactly the screen output.
If we go a bit more fancy, one could specify a desired pixel size (in real bdv coordinates) and extract the data of a capture of this "virtual" screen. Otherwise it is impossible to find out the scale of the screen recording. Or we would need the scalebar functionality and burn it into the capture.

**Comment by martinschorb** [comment]
The screenshot functionality in the current version looks already super-promising.
REALLY cool !!! @NicoKiaru 
Would it be possible to have a drop-down selector for the units available in the set of sources (plus pixels) instead of the free-text. It is always a pain to find out what exactly to type.

**Comment by martinschorb** [comment]
Aah and @tischi regarding the keyboard shortcut. Using the presets set in the "screenshot" window and then simply adding a stack slice to the generated Img+ would be the perfect funtionality.

**Comment by NicoKiaru** [comment]
> 
> 
> The screenshot functionality in the current version looks already super-promising.
> REALLY cool !!! @NicoKiaru
> Would it be possible to have a drop-down selector for the units available in the set of sources (plus pixels) instead of the free-text. It is always a pain to find out what exactly to type.

@tischi and @haesleinhuepf did this functionality. Regarding the unit I'm not so sure what could be done because one has to assume a certain unit for the bdv viewer. Most use case in microns or millimeters

**Comment by martinschorb** [comment]
OK, Kudos to these two then ;-)

I find it always hard to know what is the exact wording used in the xmls ("micrometer,micrometers,um,µm", same for nano etc...).
I think a dropdown that just shows whatever convention the present sources use would help.

**Comment by tischi** [comment]
> I think a dropdown that just shows whatever convention the present sources use would help.

@NicoKiaru I don't think we have anything for this right now, do we? I think we would need to discuss on Skype, maybe all the three of us including @martinschorb .

@martinschorb I would like to implement this:

`C` (the pretty picture mode)
One RGB image, which looks exactly like what one sees in the BigDataViewer window including all the B&C settings and colours, but with adjustable pixel size (resolution). This image cannot be modified, i.e. no brightness and contrast adjustments can be made, because it is RGB. That means all the adjustments would have to be done in BigDataViewer window beforehand.

There could be checkbox: Append to active image in ImageJ (=> implementing your movie idea).

`Shift + C` (the scientific mode)
Presents a stack of 16 bit raw data images. They are all grayscale, containing the raw pixel values. So, people could try to colour these images themselves, change brightness and contrast or just look at the raw pixel values and perform measurements.

OK?!

**Comment by martinschorb** [comment]
Hi,

I would use the existing functionality "Screenshot" for the ```Shift + C```shortcut. I like this a lot as it even preserves the LUTs.

**Comment by tischi** [comment]
> I like this a lot as it even preserves the LUTs.

Yes, but that is an issue, because we cannot easliy represent all LUTs that Bdv has in ImageJ1, because ImageJ1 LUTs are limited to 8-bit and in Bdv you can do much more fancy things.
That's why I changed it now to above described behaviour. 
I think it will be more appropriate and robust.
Let's see how you like it once it is merged.
