### ISSUE TITLE
Transform source

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#84]
I am struggling with transformations now.

Anything I do ( pressing T, calling "Manual sources Transformation" and then rotating, translating etc.) will only change the viewer not the single source with respect to the others.

What am I doing wrong?

**Comment by NicoKiaru** [comment]
Quickly:
If you press 'T', you need to have a transformed source before. Which is not the case by default in bdv-playground (it is in the default bdv). In the playground you need to wrap your source explicitely if you want. You can check whether it's wrapped with 'inspect source'.

So. If you press "Manual sources transformation", you need to select between 'mutate' and 'append'. 'append' will always work. 'mutate' will work for a transformed source and for a source from a spimdata.

Another changes in 'Manual sources transform':
* you need to click ' apply and finish '
* the source you are moving stays fiyed relative to the viewer until you click apply and finish

**Comment by tischi** [comment]
we do not manage...
our workflow is:

- right-click on a source and select "Manual sources transformation"
- choose "Append"
- then translate the source in BDV with right drag

The selected source moves, **but also all the other displayed sources move**. 
I guess this is not the intended behaviour?! That is, only the selected source should move in the viewer, isn't it?

If one however in the end clicks "Apply and finish" only the selected source moved.
@NicoKiaru

**Comment by tischi** [comment]
Also, when I afterwards want to display that source in its original position, it is still shown with the additional transform applied, even though "Append" was selected before transforming.

**Comment by NicoKiaru** [comment]
> 
> 
> we do not manage...
> our workflow is:
> 
>     * right-click on a source and select "Manual sources transformation"
> 
>     * choose "Append"
> 
>     * then translate the source in BDV with right drag
> 
> 
> The selected source moves, **but also all the other displayed sources move**.
> I guess this is not the intended behaviour?! That is, only the selected source should move in the viewer, isn't it?
> 
> If one however in the end clicks "Apply and finish" only the selected source moved.
> @NicoKiaru

Sorry, no time to check. One alternative : 
* first wrap the source (Source > Transform > Wrap as transformed Source
*  display the wrapped source (not the original one, it should be near the root in the tree display)
*  then you can use the new manual transform or the old one

**Comment by NicoKiaru** [comment]
Looks like nothing works - and it was working before.

I need to find when things broke.

**Comment by NicoKiaru** [comment]
I did something wrong in commit 3ab6470aec25a14bb265e0a0ec1b6654782cf674
I'll investigate

**Comment by NicoKiaru** [comment]
Solved in https://github.com/bigdataviewer/bigdataviewer-playground/commit/519e14a128533caf2a3b028ff040884be62394f6

Wait for the push to ImageJ update
