### ISSUE TITLE
Transform origin

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#85]
Hi,

so far the transformation origin is still the pixel origin of the input image. This means lower left corner, lowest slice. Which is not always straight-forward to find in processed data (rotations/reconstructions/...).
Is there progress in making other approaches (especially the center voxel) possible?

**Comment by NicoKiaru** [comment]
The way it works internally cannot be changed, but we can add functionality where this is hidden. We can apply a transform relative to the center of the image. Like an interactive command. What would be your use case ? A manual transformation ?
