### ISSUE TITLE
mixed Projection modes hierarchy

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#86]
Hi,

when I use mixed projection modes, BDV does not yet behave as I would expect.

Let's stay in the Light Microscopy World:
- 2 sources Brightfield (different mags/focus levels)
- 2 sources Fluorescence

what I do:
- set the BF sources to "Average"
- set the Fluo sources to "Sum"

what should happen when it calculates the resulting pixel intensity in the viewer:
- average contributions of all "Average"sources
- then AFTERWARDS add contributions of all "Sum"sources

Otherwise an all black/zero Fluo image that gets added using "Sum" will still affect the output of the "Average" contributions.

Does that make sense?

**Comment by NicoKiaru** [comment]
ping @tischi , you know more about this feature

**Comment by martinschorb** [comment]
Have you tested it also the other way round?
- When I first display the "Avg" sources and then add some "Sum" sources, they seem to darken the region.

- When I first display the "Sum" sources and then add "Avg" sources, they seem to lighten...

**Comment by tischi** [comment]
This exactly fits the kind of behaviour I would expect from the bug that I just fixed.
Let's wait until @NicoKiaru merged and deployed it.
