### ISSUE TITLE
additional Projection mode

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#87]
Hi,

when dealing with multi-scale datasets (large differences in magnification) it would make a lot of sense to have an additional projection mode that would display sources according to their resolution/voxel size.

Ideal scenario would be: 

- display these "Top-layer" sources on top of the "Average" sources but before applying the "Sum" sources.
- or make it optional whether they are shown in between "Avg" and "Sum" or on top of everything.

Cheers,
Martin

**Comment by tischi** [comment]
I managed 😄 
![image](https://user-images.githubusercontent.com/2157566/75577773-fdd34e00-5a62-11ea-8349-16da1f55eca5.png)

**Comment by NicoKiaru** [comment]
Ok, I see what exclusive means now...
