### ISSUE TITLE
Optimize zoom level for high-resolution sources

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#88]
Hi,

we experience interpolation artifacts when looking at high-resolution EM data.

I would love to have a functionality that would adjust the display zoom factor such that the interpolation would use even ratios (1:n) instead of fully flexible interpolation scales.

Example: I navigate to a source, make it the "current" source, align the display with Shift+Z. Now what would be amazing: a button/shortcut to adjust the data to screen display scaling from the current 0.4425 to 0.5 to minimize interpolation artifacts.

**Comment by NicoKiaru** [comment]
Can you post a screenshot ?

**Comment by martinschorb** [comment]
![bdv_interp](https://user-images.githubusercontent.com/35071867/75544160-abbf0800-5a23-11ea-9869-81ab1ee5a34b.png)

left is the native viewer at precisely 0.5x zoom right is bdv

**Comment by martinschorb** [comment]
you can see these line/cross-like interpolation artifacts

**Comment by NicoKiaru** [comment]
You do not want to interpolate / pressing I is not a good option ?

**Comment by martinschorb** [comment]
this screenshot is with nearest-neighbor. It only slightly gets better with tri-linear.
You can still see the crosses...

![bdv_interp1](https://user-images.githubusercontent.com/35071867/75544498-6a7b2800-5a24-11ea-9d0f-19e65b613808.png)

**Comment by NicoKiaru** [comment]
Closing the issue. See the one in mobie viewer for more info
