### ISSUE TITLE
Load sources

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#9]
Do we also want to support loading files that are not h5/xml?

**Comment by NicoKiaru** [comment]
For xml datasets which are not h5 backed, it's automatically done with XmlIOLoader, but I guess your question is about other files (tifs and so on), right ?

An idea would be to use SciFIO or bigdataviewer_bioformats ?

EDIT : No need to add bigdataviewer_bioformats : that can be used transparently, without any modification of this repository, thanks the the extensibility mechanism of bdv xml datasets

**Comment by NicoKiaru** [comment]
I'll add in `source.import` different ways to import source by copying what I had in `bigdataviewer_scijava`:
* from a file with SciFIO
* from the active IJ1 window (we have to copy what exists in `bigdataviewer_fiji`)

**Comment by tischi** [comment]
Maybe for now stick to h5/xml?
It could be a way to force people to not use too many file-formats ;-)
Also bdv will not be performant for file-formats that are not pyramidal.

**Comment by tischi** [comment]
One suggestion may be that we clearly separate the loading of 100% performant file-formats from all the others, both at the API and UI level. At the UI level I would even have a "DangerZone" menu item, where there is a "Load Sources" menu item. Because otherwise people would quickly think BDV is "not a good viewer". The Imaris people had this problem... That is why in the new version they lock it down to only opening .ims files and nothing else.
@NicoKiaru what do you think?

**Comment by NicoKiaru** [comment]
But it's not an obvious thing to do: xml datasets are extensible and use imageloader with different implementations. That's transparent for the user. Do we want to actively prevent some image loaders? I don t think it s beneficial.

**Comment by NicoKiaru** [comment]
As for IJ1 and SCIFIO, I don't know. It's pretty straightforward to add SciFIO, but at the moment there are issues with metadata (c vs z vs t), I think it's more often the issue the user will have (compared to performance). We can keep that away for the moment. No problem. IJ1 import is not working easily at the moment and what I did was super hacky, so I won't retry put something dirty in the repo, fine with me.

My suggestion : 
* let's keep xml datasets (but without imageloader filtering)
* no need to add scifio and ij1 import (not a priority)

**Comment by tischi** [comment]
I agree with both suggestions!

But don't you need support for slide-scanner data formats for your projects?

**Comment by NicoKiaru** [comment]
Yes, but that happens through the image loader extensibility mechanism. All the [`bigdataviewer-bioformats`](https://github.com/BIOP/bigdataviewer-bioformats) is fully compatible with what we do now: 
* it contains its [specific imageloader](https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/BioFormatsImageLoader.java)
* that is recognized through [an `ImgLoaderIo` annotation](https://github.com/BIOP/bigdataviewer-bioformats/blob/5a5c63a512252dbe5e8015ae2d410a5413ceb8fb/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/XmlIoBioFormatsImgLoader.java#L17-L18)

So 1 - in an IDE, adding the `bigdataviewer-bioformats` dependency will allow to use such xml specific datasets. 2 - in FIJI, if the imageloader class is in the classpath, it's the same, people will be able to use xml datasets which are not xml/hdf5 datasets (but that can still be performant)

The same command will be used: open xml file for bdv. No need to add something extra to the repository.

+ I wrote something wrong before: see my edit in a previous comment (https://github.com/bigdataviewer/bigdataviewer-playground/issues/9#issuecomment-564888221)

**Comment by NicoKiaru** [comment]
I believe this issue is solved.

@tischi please reopen if you feel that it's not the case
