### ISSUE TITLE
Projection Layers

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#95]
Potentially enhance the current "Occluding/NotOccluding" projection modes to a multi layer system.

**Comment by NicoKiaru** [comment]
started in https://github.com/bigdataviewer/bigdataviewer-playground/tree/multilayerprojection, whenever anyone wishes to continue it

**Comment by tischi** [comment]
here is some information of how it could be done:

- for 2 layers https://en.wikipedia.org/wiki/Alpha_compositing

- for more layers it seems it could be done recursively: 
![image](https://user-images.githubusercontent.com/2157566/75928510-d7e8e780-5e6e-11ea-958e-facb35fa4e00.png)

see: 

- https://koyama.xyz/project/color_unblending/download/preprint.pdf 
- https://www.w3.org/TR/2011/WD-SVGCompositing-20110315/

**Comment by NicoKiaru** [comment]
To check in bigdataviewer-playground-display. There is an alpha projection layer mechanism in there
